#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AB_K31_Radar

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK
{

// ScriptStruct AB_K31_Radar.AB_K31_Radar_C.AnimBlueprintGeneratedConstantData
// 0x017F (0x0180 - 0x0001)
struct AB_K31_Radar::FAnimBlueprintGeneratedConstantData final : public FAnimBlueprintConstantData
{
public:
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   __NameProperty_157;                                // 0x0004(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_158;                                // 0x0010(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_159;                                 // 0x001C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_160;                                // 0x0020(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_161;                                 // 0x002C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_162;                                // 0x0030(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_163;                                // 0x003C(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3D[0x3];                                       // 0x003D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   __NameProperty_164;                                // 0x0040(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_165;                                // 0x004C(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_166;                               // 0x0058(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FInputScaleBiasClampConstants          __StructProperty_167;                              // 0x005C(0x002C)(BlueprintVisible, NoDestructor)
	float                                         __FloatProperty_168;                               // 0x0088(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_169;                                // 0x008C(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAnimSyncMethod                               __EnumProperty_170;                                // 0x008D(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAnimGroupRole                                __ByteProperty_171;                                // 0x008E(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8F[0x1];                                       // 0x008F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   __NameProperty_172;                                // 0x0090(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_173;                                 // 0x009C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_174;                                // 0x00A0(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_175;                                // 0x00AC(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_176;                                 // 0x00B8(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_BC[0x4];                                       // 0x00BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNodeFunctionRef                   __StructProperty_177;                              // 0x00C0(0x0028)(BlueprintVisible, NoDestructor)
	struct FAnimSubsystem_PropertyAccess          AnimBlueprintExtension_PropertyAccess;             // 0x00E8(0x0080)()
	struct FAnimSubsystem_Base                    AnimBlueprintExtension_Base;                       // 0x0168(0x0018)()
};
static_assert(alignof(AB_K31_Radar::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on AB_K31_Radar::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(AB_K31_Radar::FAnimBlueprintGeneratedConstantData) == 0x000180, "Wrong size on AB_K31_Radar::FAnimBlueprintGeneratedConstantData");
static_assert(offsetof(AB_K31_Radar::FAnimBlueprintGeneratedConstantData, __NameProperty_157) == 0x000004, "Member 'AB_K31_Radar::FAnimBlueprintGeneratedConstantData::__NameProperty_157' has a wrong offset!");
static_assert(offsetof(AB_K31_Radar::FAnimBlueprintGeneratedConstantData, __NameProperty_158) == 0x000010, "Member 'AB_K31_Radar::FAnimBlueprintGeneratedConstantData::__NameProperty_158' has a wrong offset!");
static_assert(offsetof(AB_K31_Radar::FAnimBlueprintGeneratedConstantData, __IntProperty_159) == 0x00001C, "Member 'AB_K31_Radar::FAnimBlueprintGeneratedConstantData::__IntProperty_159' has a wrong offset!");
static_assert(offsetof(AB_K31_Radar::FAnimBlueprintGeneratedConstantData, __NameProperty_160) == 0x000020, "Member 'AB_K31_Radar::FAnimBlueprintGeneratedConstantData::__NameProperty_160' has a wrong offset!");
static_assert(offsetof(AB_K31_Radar::FAnimBlueprintGeneratedConstantData, __IntProperty_161) == 0x00002C, "Member 'AB_K31_Radar::FAnimBlueprintGeneratedConstantData::__IntProperty_161' has a wrong offset!");
static_assert(offsetof(AB_K31_Radar::FAnimBlueprintGeneratedConstantData, __NameProperty_162) == 0x000030, "Member 'AB_K31_Radar::FAnimBlueprintGeneratedConstantData::__NameProperty_162' has a wrong offset!");
static_assert(offsetof(AB_K31_Radar::FAnimBlueprintGeneratedConstantData, __BoolProperty_163) == 0x00003C, "Member 'AB_K31_Radar::FAnimBlueprintGeneratedConstantData::__BoolProperty_163' has a wrong offset!");
static_assert(offsetof(AB_K31_Radar::FAnimBlueprintGeneratedConstantData, __NameProperty_164) == 0x000040, "Member 'AB_K31_Radar::FAnimBlueprintGeneratedConstantData::__NameProperty_164' has a wrong offset!");
static_assert(offsetof(AB_K31_Radar::FAnimBlueprintGeneratedConstantData, __NameProperty_165) == 0x00004C, "Member 'AB_K31_Radar::FAnimBlueprintGeneratedConstantData::__NameProperty_165' has a wrong offset!");
static_assert(offsetof(AB_K31_Radar::FAnimBlueprintGeneratedConstantData, __FloatProperty_166) == 0x000058, "Member 'AB_K31_Radar::FAnimBlueprintGeneratedConstantData::__FloatProperty_166' has a wrong offset!");
static_assert(offsetof(AB_K31_Radar::FAnimBlueprintGeneratedConstantData, __StructProperty_167) == 0x00005C, "Member 'AB_K31_Radar::FAnimBlueprintGeneratedConstantData::__StructProperty_167' has a wrong offset!");
static_assert(offsetof(AB_K31_Radar::FAnimBlueprintGeneratedConstantData, __FloatProperty_168) == 0x000088, "Member 'AB_K31_Radar::FAnimBlueprintGeneratedConstantData::__FloatProperty_168' has a wrong offset!");
static_assert(offsetof(AB_K31_Radar::FAnimBlueprintGeneratedConstantData, __BoolProperty_169) == 0x00008C, "Member 'AB_K31_Radar::FAnimBlueprintGeneratedConstantData::__BoolProperty_169' has a wrong offset!");
static_assert(offsetof(AB_K31_Radar::FAnimBlueprintGeneratedConstantData, __EnumProperty_170) == 0x00008D, "Member 'AB_K31_Radar::FAnimBlueprintGeneratedConstantData::__EnumProperty_170' has a wrong offset!");
static_assert(offsetof(AB_K31_Radar::FAnimBlueprintGeneratedConstantData, __ByteProperty_171) == 0x00008E, "Member 'AB_K31_Radar::FAnimBlueprintGeneratedConstantData::__ByteProperty_171' has a wrong offset!");
static_assert(offsetof(AB_K31_Radar::FAnimBlueprintGeneratedConstantData, __NameProperty_172) == 0x000090, "Member 'AB_K31_Radar::FAnimBlueprintGeneratedConstantData::__NameProperty_172' has a wrong offset!");
static_assert(offsetof(AB_K31_Radar::FAnimBlueprintGeneratedConstantData, __IntProperty_173) == 0x00009C, "Member 'AB_K31_Radar::FAnimBlueprintGeneratedConstantData::__IntProperty_173' has a wrong offset!");
static_assert(offsetof(AB_K31_Radar::FAnimBlueprintGeneratedConstantData, __NameProperty_174) == 0x0000A0, "Member 'AB_K31_Radar::FAnimBlueprintGeneratedConstantData::__NameProperty_174' has a wrong offset!");
static_assert(offsetof(AB_K31_Radar::FAnimBlueprintGeneratedConstantData, __NameProperty_175) == 0x0000AC, "Member 'AB_K31_Radar::FAnimBlueprintGeneratedConstantData::__NameProperty_175' has a wrong offset!");
static_assert(offsetof(AB_K31_Radar::FAnimBlueprintGeneratedConstantData, __IntProperty_176) == 0x0000B8, "Member 'AB_K31_Radar::FAnimBlueprintGeneratedConstantData::__IntProperty_176' has a wrong offset!");
static_assert(offsetof(AB_K31_Radar::FAnimBlueprintGeneratedConstantData, __StructProperty_177) == 0x0000C0, "Member 'AB_K31_Radar::FAnimBlueprintGeneratedConstantData::__StructProperty_177' has a wrong offset!");
static_assert(offsetof(AB_K31_Radar::FAnimBlueprintGeneratedConstantData, AnimBlueprintExtension_PropertyAccess) == 0x0000E8, "Member 'AB_K31_Radar::FAnimBlueprintGeneratedConstantData::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(AB_K31_Radar::FAnimBlueprintGeneratedConstantData, AnimBlueprintExtension_Base) == 0x000168, "Member 'AB_K31_Radar::FAnimBlueprintGeneratedConstantData::AnimBlueprintExtension_Base' has a wrong offset!");

// ScriptStruct AB_K31_Radar.AB_K31_Radar_C.AnimBlueprintGeneratedMutableData
// 0x0000 (0x0001 - 0x0001)
struct AB_K31_Radar::FAnimBlueprintGeneratedMutableData final : public FAnimBlueprintMutableData
{
};
static_assert(alignof(AB_K31_Radar::FAnimBlueprintGeneratedMutableData) == 0x000001, "Wrong alignment on AB_K31_Radar::FAnimBlueprintGeneratedMutableData");
static_assert(sizeof(AB_K31_Radar::FAnimBlueprintGeneratedMutableData) == 0x000001, "Wrong size on AB_K31_Radar::FAnimBlueprintGeneratedMutableData");

}

