#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AB_Lute_S42

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Enum_CamperMenuAnimationState_structs.hpp"


namespace SDK::Params
{

// Function AB_Lute_S42.AB_Lute_S42_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct AB_Lute_S42_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
static_assert(alignof(AB_Lute_S42_C_AnimGraph) == 0x000008, "Wrong alignment on AB_Lute_S42_C_AnimGraph");
static_assert(sizeof(AB_Lute_S42_C_AnimGraph) == 0x000010, "Wrong size on AB_Lute_S42_C_AnimGraph");
static_assert(offsetof(AB_Lute_S42_C_AnimGraph, AnimGraph_0) == 0x000000, "Member 'AB_Lute_S42_C_AnimGraph::AnimGraph_0' has a wrong offset!");

// Function AB_Lute_S42.AB_Lute_S42_C.ExecuteUbergraph_AB_Lute_S42
// 0x0030 (0x0030 - 0x0000)
struct AB_Lute_S42_C_ExecuteUbergraph_AB_Lute_S42 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(Enum_CamperMenuAnimationState State)> K2Node_CreateDelegate_OutputDelegate;       // 0x0004(0x0014)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_TryGetPawnOwner_ReturnValue;              // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_Menu_CamperMale21_C*                K2Node_DynamicCast_AsBP_Menu_Camper_Male_21;       // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	Enum_CamperMenuAnimationState                 K2Node_CustomEvent_State;                          // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AB_Lute_S42_C_ExecuteUbergraph_AB_Lute_S42) == 0x000008, "Wrong alignment on AB_Lute_S42_C_ExecuteUbergraph_AB_Lute_S42");
static_assert(sizeof(AB_Lute_S42_C_ExecuteUbergraph_AB_Lute_S42) == 0x000030, "Wrong size on AB_Lute_S42_C_ExecuteUbergraph_AB_Lute_S42");
static_assert(offsetof(AB_Lute_S42_C_ExecuteUbergraph_AB_Lute_S42, EntryPoint) == 0x000000, "Member 'AB_Lute_S42_C_ExecuteUbergraph_AB_Lute_S42::EntryPoint' has a wrong offset!");
static_assert(offsetof(AB_Lute_S42_C_ExecuteUbergraph_AB_Lute_S42, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'AB_Lute_S42_C_ExecuteUbergraph_AB_Lute_S42::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(AB_Lute_S42_C_ExecuteUbergraph_AB_Lute_S42, CallFunc_TryGetPawnOwner_ReturnValue) == 0x000018, "Member 'AB_Lute_S42_C_ExecuteUbergraph_AB_Lute_S42::CallFunc_TryGetPawnOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(AB_Lute_S42_C_ExecuteUbergraph_AB_Lute_S42, K2Node_DynamicCast_AsBP_Menu_Camper_Male_21) == 0x000020, "Member 'AB_Lute_S42_C_ExecuteUbergraph_AB_Lute_S42::K2Node_DynamicCast_AsBP_Menu_Camper_Male_21' has a wrong offset!");
static_assert(offsetof(AB_Lute_S42_C_ExecuteUbergraph_AB_Lute_S42, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'AB_Lute_S42_C_ExecuteUbergraph_AB_Lute_S42::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(AB_Lute_S42_C_ExecuteUbergraph_AB_Lute_S42, K2Node_CustomEvent_State) == 0x000029, "Member 'AB_Lute_S42_C_ExecuteUbergraph_AB_Lute_S42::K2Node_CustomEvent_State' has a wrong offset!");

// Function AB_Lute_S42.AB_Lute_S42_C.OnMenuAnimationStateChange_Event
// 0x0001 (0x0001 - 0x0000)
struct AB_Lute_S42_C_OnMenuAnimationStateChange_Event final
{
public:
	Enum_CamperMenuAnimationState                 State;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AB_Lute_S42_C_OnMenuAnimationStateChange_Event) == 0x000001, "Wrong alignment on AB_Lute_S42_C_OnMenuAnimationStateChange_Event");
static_assert(sizeof(AB_Lute_S42_C_OnMenuAnimationStateChange_Event) == 0x000001, "Wrong size on AB_Lute_S42_C_OnMenuAnimationStateChange_Event");
static_assert(offsetof(AB_Lute_S42_C_OnMenuAnimationStateChange_Event, State) == 0x000000, "Member 'AB_Lute_S42_C_OnMenuAnimationStateChange_Event::State' has a wrong offset!");

}

