#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AB_Menu_Slasher34

#include "Basic.hpp"

#include "AnimGraphRuntime_structs.hpp"
#include "Engine_structs.hpp"
#include "DBDAnimation_classes.hpp"
#include "AB_Menu_Slasher34_structs.hpp"
#include "DeadByDaylight_structs.hpp"
#include "Aset_Slasher_Menu_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass AB_Menu_Slasher34.AB_Menu_Slasher34_C
// 0x0370 (0x0700 - 0x0390)
class UAB_Menu_Slasher34_C final : public UBaseMenuAnimInstance
{
public:
	uint8                                         Pad_388[0x8];                                      // 0x0388(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0390(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct AB_Menu_Slasher34::FAnimBlueprintGeneratedMutableData __AnimBlueprintMutables;            // 0x0398(0x0002)(HasGetValueTypeHash)
	uint8                                         Pad_39A[0x6];                                      // 0x039A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Tag;                        // 0x03A0(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x03A8(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x03B0(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x03B8(0x0020)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult;                    // 0x03D8(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x0400(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1;                       // 0x0448(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x0468(0x0048)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool;                     // 0x04B0(0x0048)()
	struct FAnimNode_LinkedAnimGraph              AnimGraphNode_LinkedAnimGraph;                     // 0x04F8(0x00B8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0x05B0(0x0020)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0x05D0(0x00C8)()
	class ABP_Menu_Slasher34_C*                   KillerBP;                                          // 0x0698(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FAset_Slasher_Menu                     MenuAnimSet;                                       // 0x06A0(0x0050)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	EGameFlowStep                                 CurrentMenu;                                       // 0x06F0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsInStore;                                         // 0x06F1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void BlueprintInitializeAnimation();
	void BlueprintLinkedAnimationLayersInitialized();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Menu_Slasher34_AnimGraphNode_TransitionResult_9A66974D44E2A6F3C72019A62C0BBCF8();
	void ExecuteUbergraph_AB_Menu_Slasher34(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AB_Menu_Slasher34_C">();
	}
	static class UAB_Menu_Slasher34_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAB_Menu_Slasher34_C>();
	}
};
static_assert(alignof(UAB_Menu_Slasher34_C) == 0x000010, "Wrong alignment on UAB_Menu_Slasher34_C");
static_assert(sizeof(UAB_Menu_Slasher34_C) == 0x000700, "Wrong size on UAB_Menu_Slasher34_C");
static_assert(offsetof(UAB_Menu_Slasher34_C, UberGraphFrame) == 0x000390, "Member 'UAB_Menu_Slasher34_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher34_C, __AnimBlueprintMutables) == 0x000398, "Member 'UAB_Menu_Slasher34_C::__AnimBlueprintMutables' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher34_C, AnimBlueprintExtension_Tag) == 0x0003A0, "Member 'UAB_Menu_Slasher34_C::AnimBlueprintExtension_Tag' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher34_C, AnimBlueprintExtension_PropertyAccess) == 0x0003A8, "Member 'UAB_Menu_Slasher34_C::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher34_C, AnimBlueprintExtension_Base) == 0x0003B0, "Member 'UAB_Menu_Slasher34_C::AnimBlueprintExtension_Base' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher34_C, AnimGraphNode_Root) == 0x0003B8, "Member 'UAB_Menu_Slasher34_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher34_C, AnimGraphNode_TransitionResult) == 0x0003D8, "Member 'UAB_Menu_Slasher34_C::AnimGraphNode_TransitionResult' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher34_C, AnimGraphNode_SequencePlayer_1) == 0x000400, "Member 'UAB_Menu_Slasher34_C::AnimGraphNode_SequencePlayer_1' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher34_C, AnimGraphNode_StateResult_1) == 0x000448, "Member 'UAB_Menu_Slasher34_C::AnimGraphNode_StateResult_1' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher34_C, AnimGraphNode_SequencePlayer) == 0x000468, "Member 'UAB_Menu_Slasher34_C::AnimGraphNode_SequencePlayer' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher34_C, AnimGraphNode_BlendListByBool) == 0x0004B0, "Member 'UAB_Menu_Slasher34_C::AnimGraphNode_BlendListByBool' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher34_C, AnimGraphNode_LinkedAnimGraph) == 0x0004F8, "Member 'UAB_Menu_Slasher34_C::AnimGraphNode_LinkedAnimGraph' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher34_C, AnimGraphNode_StateResult) == 0x0005B0, "Member 'UAB_Menu_Slasher34_C::AnimGraphNode_StateResult' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher34_C, AnimGraphNode_StateMachine) == 0x0005D0, "Member 'UAB_Menu_Slasher34_C::AnimGraphNode_StateMachine' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher34_C, KillerBP) == 0x000698, "Member 'UAB_Menu_Slasher34_C::KillerBP' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher34_C, MenuAnimSet) == 0x0006A0, "Member 'UAB_Menu_Slasher34_C::MenuAnimSet' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher34_C, CurrentMenu) == 0x0006F0, "Member 'UAB_Menu_Slasher34_C::CurrentMenu' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher34_C, IsInStore) == 0x0006F1, "Member 'UAB_Menu_Slasher34_C::IsInStore' has a wrong offset!");

}

