#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AB_Menu_Slasher04

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Aset_Slasher_Menu_structs.hpp"
#include "DBDAnimation_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass AB_Menu_Slasher04.AB_Menu_Slasher04_C
// 0x0150 (0x04E0 - 0x0390)
class UAB_Menu_Slasher04_C final : public UBaseMenuAnimInstance
{
public:
	uint8                                         Pad_388[0x8];                                      // 0x0388(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0390(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Tag;                        // 0x0398(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x03A0(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x03A8(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x03B0(0x0020)()
	struct FAnimNode_LinkedAnimGraph              AnimGraphNode_LinkedAnimGraph;                     // 0x03D0(0x00B8)()
	struct FAset_Slasher_Menu                     MenuAnimSet;                                       // 0x0488(0x0050)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void BlueprintLinkedAnimationLayersInitialized();
	void ExecuteUbergraph_AB_Menu_Slasher04(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AB_Menu_Slasher04_C">();
	}
	static class UAB_Menu_Slasher04_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAB_Menu_Slasher04_C>();
	}
};
static_assert(alignof(UAB_Menu_Slasher04_C) == 0x000010, "Wrong alignment on UAB_Menu_Slasher04_C");
static_assert(sizeof(UAB_Menu_Slasher04_C) == 0x0004E0, "Wrong size on UAB_Menu_Slasher04_C");
static_assert(offsetof(UAB_Menu_Slasher04_C, UberGraphFrame) == 0x000390, "Member 'UAB_Menu_Slasher04_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher04_C, AnimBlueprintExtension_Tag) == 0x000398, "Member 'UAB_Menu_Slasher04_C::AnimBlueprintExtension_Tag' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher04_C, AnimBlueprintExtension_PropertyAccess) == 0x0003A0, "Member 'UAB_Menu_Slasher04_C::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher04_C, AnimBlueprintExtension_Base) == 0x0003A8, "Member 'UAB_Menu_Slasher04_C::AnimBlueprintExtension_Base' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher04_C, AnimGraphNode_Root) == 0x0003B0, "Member 'UAB_Menu_Slasher04_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher04_C, AnimGraphNode_LinkedAnimGraph) == 0x0003D0, "Member 'UAB_Menu_Slasher04_C::AnimGraphNode_LinkedAnimGraph' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher04_C, MenuAnimSet) == 0x000488, "Member 'UAB_Menu_Slasher04_C::MenuAnimSet' has a wrong offset!");

}

