#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AB_Menu_Slasher30

#include "Basic.hpp"

#include "AB_Menu_Slasher30_classes.hpp"
#include "AB_Menu_Slasher30_parameters.hpp"


namespace SDK
{

// Function AB_Menu_Slasher30.AB_Menu_Slasher30_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UAB_Menu_Slasher30_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Menu_Slasher30_C", "AnimGraph");

	Params::AB_Menu_Slasher30_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function AB_Menu_Slasher30.AB_Menu_Slasher30_C.BlueprintLinkedAnimationLayersInitialized
// (Event, Public, BlueprintEvent)

void UAB_Menu_Slasher30_C::BlueprintLinkedAnimationLayersInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Menu_Slasher30_C", "BlueprintLinkedAnimationLayersInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Menu_Slasher30.AB_Menu_Slasher30_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Menu_Slasher30_AnimGraphNode_TransitionResult_956F39ED48CD98A09FE24DAA729BAA00
// (BlueprintEvent)

void UAB_Menu_Slasher30_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Menu_Slasher30_AnimGraphNode_TransitionResult_956F39ED48CD98A09FE24DAA729BAA00()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Menu_Slasher30_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Menu_Slasher30_AnimGraphNode_TransitionResult_956F39ED48CD98A09FE24DAA729BAA00");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Menu_Slasher30.AB_Menu_Slasher30_C.ExecuteUbergraph_AB_Menu_Slasher30
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAB_Menu_Slasher30_C::ExecuteUbergraph_AB_Menu_Slasher30(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Menu_Slasher30_C", "ExecuteUbergraph_AB_Menu_Slasher30");

	Params::AB_Menu_Slasher30_C_ExecuteUbergraph_AB_Menu_Slasher30 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

