#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AB_Menu_Slasher29

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Enum_MenuAnimationState_structs.hpp"
#include "DeadByDaylight_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function AB_Menu_Slasher29.AB_Menu_Slasher29_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct AB_Menu_Slasher29_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
static_assert(alignof(AB_Menu_Slasher29_C_AnimGraph) == 0x000008, "Wrong alignment on AB_Menu_Slasher29_C_AnimGraph");
static_assert(sizeof(AB_Menu_Slasher29_C_AnimGraph) == 0x000010, "Wrong size on AB_Menu_Slasher29_C_AnimGraph");
static_assert(offsetof(AB_Menu_Slasher29_C_AnimGraph, AnimGraph_0) == 0x000000, "Member 'AB_Menu_Slasher29_C_AnimGraph::AnimGraph_0' has a wrong offset!");

// Function AB_Menu_Slasher29.AB_Menu_Slasher29_C.BlueprintUpdateAnimation
// 0x0004 (0x0004 - 0x0000)
struct AB_Menu_Slasher29_C_BlueprintUpdateAnimation final
{
public:
	float                                         DeltaTimeX;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AB_Menu_Slasher29_C_BlueprintUpdateAnimation) == 0x000004, "Wrong alignment on AB_Menu_Slasher29_C_BlueprintUpdateAnimation");
static_assert(sizeof(AB_Menu_Slasher29_C_BlueprintUpdateAnimation) == 0x000004, "Wrong size on AB_Menu_Slasher29_C_BlueprintUpdateAnimation");
static_assert(offsetof(AB_Menu_Slasher29_C_BlueprintUpdateAnimation, DeltaTimeX) == 0x000000, "Member 'AB_Menu_Slasher29_C_BlueprintUpdateAnimation::DeltaTimeX' has a wrong offset!");

// Function AB_Menu_Slasher29.AB_Menu_Slasher29_C.ExecuteUbergraph_AB_Menu_Slasher29
// 0x0150 (0x0150 - 0x0000)
struct AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_4;                   // 0x0004(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_3;                   // 0x0010(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate;              // 0x001C(0x0014)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_2;                   // 0x0030(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_1;            // 0x003C(0x0014)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_1;                   // 0x0050(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_2;            // 0x005C(0x0014)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName;                     // 0x0070(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_3;            // 0x007C(0x0014)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   Temp_name_Variable;                                // 0x0090(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetRelevantAnimTimeRemaining_ReturnValue; // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_DoubleDouble_ReturnValue;            // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A1[0x3];                                       // 0x00A1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Event_DeltaTimeX;                           // 0x00A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_Menu_Slasher29_C*                   K2Node_DynamicCast_AsBP_Menu_Slasher_29;           // 0x00A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x00B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x00B2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B3[0x5];                                       // 0x00B3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_TryGetPawnOwner_ReturnValue;              // 0x00B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	EGameFlowStep                                 CallFunc_GetCurrentMenu_ReturnValue;               // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C1[0x7];                                       // 0x00C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ADBDMenuPlayer*                         K2Node_DynamicCast_AsDBDMenu_Player;               // 0x00C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D1[0x7];                                       // 0x00D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetLinkedAnimGraphInstanceByTag_ReturnValue; // 0x00D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_AB_Slasher_SubGraph_Menu_C> K2Node_DynamicCast_AsBPI_AB_Slasher_Sub_Graph_Menu; // 0x00E0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F1[0x3];                                       // 0x00F1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_4;            // 0x00F4(0x0014)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	Enum_MenuAnimationState                       K2Node_CustomEvent_State;                          // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0109(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_10A[0x2];                                      // 0x010A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(Enum_MenuAnimationState State)> K2Node_CreateDelegate_OutputDelegate_5;           // 0x010C(0x0014)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_K2_GetActorRotation_ReturnValue;          // 0x0120(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UPlayMontageCallbackProxy*              CallFunc_CreateProxyObjectForPlayMontage_ReturnValue; // 0x0138(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_K2_SetActorRotation_ReturnValue;          // 0x0141(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_142[0x6];                                      // 0x0142(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Less_DoubleDouble_A_ImplicitCast;         // 0x0148(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29) == 0x000008, "Wrong alignment on AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29");
static_assert(sizeof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29) == 0x000150, "Wrong size on AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, EntryPoint) == 0x000000, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::EntryPoint' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, K2Node_CustomEvent_NotifyName_4) == 0x000004, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::K2Node_CustomEvent_NotifyName_4' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, K2Node_CustomEvent_NotifyName_3) == 0x000010, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::K2Node_CustomEvent_NotifyName_3' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, K2Node_CreateDelegate_OutputDelegate) == 0x00001C, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, K2Node_CustomEvent_NotifyName_2) == 0x000030, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::K2Node_CustomEvent_NotifyName_2' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, K2Node_CreateDelegate_OutputDelegate_1) == 0x00003C, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, K2Node_CustomEvent_NotifyName_1) == 0x000050, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::K2Node_CustomEvent_NotifyName_1' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, K2Node_CreateDelegate_OutputDelegate_2) == 0x00005C, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, K2Node_CustomEvent_NotifyName) == 0x000070, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::K2Node_CustomEvent_NotifyName' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, K2Node_CreateDelegate_OutputDelegate_3) == 0x00007C, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, Temp_name_Variable) == 0x000090, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::Temp_name_Variable' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, CallFunc_GetRelevantAnimTimeRemaining_ReturnValue) == 0x00009C, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::CallFunc_GetRelevantAnimTimeRemaining_ReturnValue' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, CallFunc_Less_DoubleDouble_ReturnValue) == 0x0000A0, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::CallFunc_Less_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, K2Node_Event_DeltaTimeX) == 0x0000A4, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::K2Node_Event_DeltaTimeX' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, K2Node_DynamicCast_AsBP_Menu_Slasher_29) == 0x0000A8, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::K2Node_DynamicCast_AsBP_Menu_Slasher_29' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, K2Node_DynamicCast_bSuccess) == 0x0000B0, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x0000B1, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, CallFunc_BooleanOR_ReturnValue) == 0x0000B2, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, CallFunc_TryGetPawnOwner_ReturnValue) == 0x0000B8, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::CallFunc_TryGetPawnOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, CallFunc_GetCurrentMenu_ReturnValue) == 0x0000C0, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::CallFunc_GetCurrentMenu_ReturnValue' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, K2Node_DynamicCast_AsDBDMenu_Player) == 0x0000C8, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::K2Node_DynamicCast_AsDBDMenu_Player' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, K2Node_DynamicCast_bSuccess_1) == 0x0000D0, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, CallFunc_GetLinkedAnimGraphInstanceByTag_ReturnValue) == 0x0000D8, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::CallFunc_GetLinkedAnimGraphInstanceByTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, K2Node_DynamicCast_AsBPI_AB_Slasher_Sub_Graph_Menu) == 0x0000E0, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::K2Node_DynamicCast_AsBPI_AB_Slasher_Sub_Graph_Menu' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, K2Node_DynamicCast_bSuccess_2) == 0x0000F0, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, K2Node_CreateDelegate_OutputDelegate_4) == 0x0000F4, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, K2Node_CustomEvent_State) == 0x000108, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::K2Node_CustomEvent_State' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000109, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, K2Node_CreateDelegate_OutputDelegate_5) == 0x00010C, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, CallFunc_K2_GetActorRotation_ReturnValue) == 0x000120, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::CallFunc_K2_GetActorRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, CallFunc_CreateProxyObjectForPlayMontage_ReturnValue) == 0x000138, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::CallFunc_CreateProxyObjectForPlayMontage_ReturnValue' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, CallFunc_IsValid_ReturnValue) == 0x000140, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, CallFunc_K2_SetActorRotation_ReturnValue) == 0x000141, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::CallFunc_K2_SetActorRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29, CallFunc_Less_DoubleDouble_A_ImplicitCast) == 0x000148, "Member 'AB_Menu_Slasher29_C_ExecuteUbergraph_AB_Menu_Slasher29::CallFunc_Less_DoubleDouble_A_ImplicitCast' has a wrong offset!");

// Function AB_Menu_Slasher29.AB_Menu_Slasher29_C.OnBlendOut_BCF96FA845C80945BE477B87CA56E35A
// 0x000C (0x000C - 0x0000)
struct AB_Menu_Slasher29_C_OnBlendOut_BCF96FA845C80945BE477B87CA56E35A final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AB_Menu_Slasher29_C_OnBlendOut_BCF96FA845C80945BE477B87CA56E35A) == 0x000004, "Wrong alignment on AB_Menu_Slasher29_C_OnBlendOut_BCF96FA845C80945BE477B87CA56E35A");
static_assert(sizeof(AB_Menu_Slasher29_C_OnBlendOut_BCF96FA845C80945BE477B87CA56E35A) == 0x00000C, "Wrong size on AB_Menu_Slasher29_C_OnBlendOut_BCF96FA845C80945BE477B87CA56E35A");
static_assert(offsetof(AB_Menu_Slasher29_C_OnBlendOut_BCF96FA845C80945BE477B87CA56E35A, NotifyName) == 0x000000, "Member 'AB_Menu_Slasher29_C_OnBlendOut_BCF96FA845C80945BE477B87CA56E35A::NotifyName' has a wrong offset!");

// Function AB_Menu_Slasher29.AB_Menu_Slasher29_C.OnCompleted_BCF96FA845C80945BE477B87CA56E35A
// 0x000C (0x000C - 0x0000)
struct AB_Menu_Slasher29_C_OnCompleted_BCF96FA845C80945BE477B87CA56E35A final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AB_Menu_Slasher29_C_OnCompleted_BCF96FA845C80945BE477B87CA56E35A) == 0x000004, "Wrong alignment on AB_Menu_Slasher29_C_OnCompleted_BCF96FA845C80945BE477B87CA56E35A");
static_assert(sizeof(AB_Menu_Slasher29_C_OnCompleted_BCF96FA845C80945BE477B87CA56E35A) == 0x00000C, "Wrong size on AB_Menu_Slasher29_C_OnCompleted_BCF96FA845C80945BE477B87CA56E35A");
static_assert(offsetof(AB_Menu_Slasher29_C_OnCompleted_BCF96FA845C80945BE477B87CA56E35A, NotifyName) == 0x000000, "Member 'AB_Menu_Slasher29_C_OnCompleted_BCF96FA845C80945BE477B87CA56E35A::NotifyName' has a wrong offset!");

// Function AB_Menu_Slasher29.AB_Menu_Slasher29_C.OnInterrupted_BCF96FA845C80945BE477B87CA56E35A
// 0x000C (0x000C - 0x0000)
struct AB_Menu_Slasher29_C_OnInterrupted_BCF96FA845C80945BE477B87CA56E35A final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AB_Menu_Slasher29_C_OnInterrupted_BCF96FA845C80945BE477B87CA56E35A) == 0x000004, "Wrong alignment on AB_Menu_Slasher29_C_OnInterrupted_BCF96FA845C80945BE477B87CA56E35A");
static_assert(sizeof(AB_Menu_Slasher29_C_OnInterrupted_BCF96FA845C80945BE477B87CA56E35A) == 0x00000C, "Wrong size on AB_Menu_Slasher29_C_OnInterrupted_BCF96FA845C80945BE477B87CA56E35A");
static_assert(offsetof(AB_Menu_Slasher29_C_OnInterrupted_BCF96FA845C80945BE477B87CA56E35A, NotifyName) == 0x000000, "Member 'AB_Menu_Slasher29_C_OnInterrupted_BCF96FA845C80945BE477B87CA56E35A::NotifyName' has a wrong offset!");

// Function AB_Menu_Slasher29.AB_Menu_Slasher29_C.OnMenuAnimationStateChange_Event
// 0x0001 (0x0001 - 0x0000)
struct AB_Menu_Slasher29_C_OnMenuAnimationStateChange_Event final
{
public:
	Enum_MenuAnimationState                       State;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AB_Menu_Slasher29_C_OnMenuAnimationStateChange_Event) == 0x000001, "Wrong alignment on AB_Menu_Slasher29_C_OnMenuAnimationStateChange_Event");
static_assert(sizeof(AB_Menu_Slasher29_C_OnMenuAnimationStateChange_Event) == 0x000001, "Wrong size on AB_Menu_Slasher29_C_OnMenuAnimationStateChange_Event");
static_assert(offsetof(AB_Menu_Slasher29_C_OnMenuAnimationStateChange_Event, State) == 0x000000, "Member 'AB_Menu_Slasher29_C_OnMenuAnimationStateChange_Event::State' has a wrong offset!");

// Function AB_Menu_Slasher29.AB_Menu_Slasher29_C.OnNotifyBegin_BCF96FA845C80945BE477B87CA56E35A
// 0x000C (0x000C - 0x0000)
struct AB_Menu_Slasher29_C_OnNotifyBegin_BCF96FA845C80945BE477B87CA56E35A final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AB_Menu_Slasher29_C_OnNotifyBegin_BCF96FA845C80945BE477B87CA56E35A) == 0x000004, "Wrong alignment on AB_Menu_Slasher29_C_OnNotifyBegin_BCF96FA845C80945BE477B87CA56E35A");
static_assert(sizeof(AB_Menu_Slasher29_C_OnNotifyBegin_BCF96FA845C80945BE477B87CA56E35A) == 0x00000C, "Wrong size on AB_Menu_Slasher29_C_OnNotifyBegin_BCF96FA845C80945BE477B87CA56E35A");
static_assert(offsetof(AB_Menu_Slasher29_C_OnNotifyBegin_BCF96FA845C80945BE477B87CA56E35A, NotifyName) == 0x000000, "Member 'AB_Menu_Slasher29_C_OnNotifyBegin_BCF96FA845C80945BE477B87CA56E35A::NotifyName' has a wrong offset!");

// Function AB_Menu_Slasher29.AB_Menu_Slasher29_C.OnNotifyEnd_BCF96FA845C80945BE477B87CA56E35A
// 0x000C (0x000C - 0x0000)
struct AB_Menu_Slasher29_C_OnNotifyEnd_BCF96FA845C80945BE477B87CA56E35A final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AB_Menu_Slasher29_C_OnNotifyEnd_BCF96FA845C80945BE477B87CA56E35A) == 0x000004, "Wrong alignment on AB_Menu_Slasher29_C_OnNotifyEnd_BCF96FA845C80945BE477B87CA56E35A");
static_assert(sizeof(AB_Menu_Slasher29_C_OnNotifyEnd_BCF96FA845C80945BE477B87CA56E35A) == 0x00000C, "Wrong size on AB_Menu_Slasher29_C_OnNotifyEnd_BCF96FA845C80945BE477B87CA56E35A");
static_assert(offsetof(AB_Menu_Slasher29_C_OnNotifyEnd_BCF96FA845C80945BE477B87CA56E35A, NotifyName) == 0x000000, "Member 'AB_Menu_Slasher29_C_OnNotifyEnd_BCF96FA845C80945BE477B87CA56E35A::NotifyName' has a wrong offset!");

}

