#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AB_Menu_Slasher29

#include "Basic.hpp"

#include "Enum_MenuAnimationState_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "Engine_structs.hpp"
#include "DBDAnimation_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "Aset_Slasher_Menu_structs.hpp"
#include "DeadByDaylight_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass AB_Menu_Slasher29.AB_Menu_Slasher29_C
// 0x02F0 (0x0680 - 0x0390)
class UAB_Menu_Slasher29_C final : public UBaseMenuAnimInstance
{
public:
	uint8                                         Pad_388[0x8];                                      // 0x0388(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0390(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Tag;                        // 0x0398(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x03A0(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x03A8(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x03B0(0x0020)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult;                    // 0x03D0(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x03F8(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1;                       // 0x0440(0x0020)()
	struct FAnimNode_LinkedAnimGraph              AnimGraphNode_LinkedAnimGraph;                     // 0x0460(0x00B8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0x0518(0x0020)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0x0538(0x00C8)()
	struct FRotator                               StartRot;                                          // 0x0600(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	class ABP_Menu_Slasher29_C*                   As_BP_Menu_Slasher_29;                             // 0x0618(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class ADBDMenuPlayer*                         As_DBDMenu_Player;                                 // 0x0620(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	EGameFlowStep                                 CurrentMenu;                                       // 0x0628(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_629[0x7];                                      // 0x0629(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAset_Slasher_Menu                     AnimSet;                                           // 0x0630(0x0050)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void AnimNotify_EnableCloth();
	void BlueprintInitializeAnimation();
	void BlueprintLinkedAnimationLayersInitialized();
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Menu_Slasher29_AnimGraphNode_TransitionResult_F96CE72F4B81CD8FE3BFCB8F5B7DE07F();
	void ExecuteUbergraph_AB_Menu_Slasher29(int32 EntryPoint);
	void OnBlendOut_BCF96FA845C80945BE477B87CA56E35A(class FName NotifyName);
	void OnCompleted_BCF96FA845C80945BE477B87CA56E35A(class FName NotifyName);
	void OnInterrupted_BCF96FA845C80945BE477B87CA56E35A(class FName NotifyName);
	void OnMenuAnimationStateChange_Event(Enum_MenuAnimationState State);
	void OnNotifyBegin_BCF96FA845C80945BE477B87CA56E35A(class FName NotifyName);
	void OnNotifyEnd_BCF96FA845C80945BE477B87CA56E35A(class FName NotifyName);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AB_Menu_Slasher29_C">();
	}
	static class UAB_Menu_Slasher29_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAB_Menu_Slasher29_C>();
	}
};
static_assert(alignof(UAB_Menu_Slasher29_C) == 0x000010, "Wrong alignment on UAB_Menu_Slasher29_C");
static_assert(sizeof(UAB_Menu_Slasher29_C) == 0x000680, "Wrong size on UAB_Menu_Slasher29_C");
static_assert(offsetof(UAB_Menu_Slasher29_C, UberGraphFrame) == 0x000390, "Member 'UAB_Menu_Slasher29_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher29_C, AnimBlueprintExtension_Tag) == 0x000398, "Member 'UAB_Menu_Slasher29_C::AnimBlueprintExtension_Tag' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher29_C, AnimBlueprintExtension_PropertyAccess) == 0x0003A0, "Member 'UAB_Menu_Slasher29_C::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher29_C, AnimBlueprintExtension_Base) == 0x0003A8, "Member 'UAB_Menu_Slasher29_C::AnimBlueprintExtension_Base' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher29_C, AnimGraphNode_Root) == 0x0003B0, "Member 'UAB_Menu_Slasher29_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher29_C, AnimGraphNode_TransitionResult) == 0x0003D0, "Member 'UAB_Menu_Slasher29_C::AnimGraphNode_TransitionResult' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher29_C, AnimGraphNode_SequencePlayer) == 0x0003F8, "Member 'UAB_Menu_Slasher29_C::AnimGraphNode_SequencePlayer' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher29_C, AnimGraphNode_StateResult_1) == 0x000440, "Member 'UAB_Menu_Slasher29_C::AnimGraphNode_StateResult_1' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher29_C, AnimGraphNode_LinkedAnimGraph) == 0x000460, "Member 'UAB_Menu_Slasher29_C::AnimGraphNode_LinkedAnimGraph' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher29_C, AnimGraphNode_StateResult) == 0x000518, "Member 'UAB_Menu_Slasher29_C::AnimGraphNode_StateResult' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher29_C, AnimGraphNode_StateMachine) == 0x000538, "Member 'UAB_Menu_Slasher29_C::AnimGraphNode_StateMachine' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher29_C, StartRot) == 0x000600, "Member 'UAB_Menu_Slasher29_C::StartRot' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher29_C, As_BP_Menu_Slasher_29) == 0x000618, "Member 'UAB_Menu_Slasher29_C::As_BP_Menu_Slasher_29' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher29_C, As_DBDMenu_Player) == 0x000620, "Member 'UAB_Menu_Slasher29_C::As_DBDMenu_Player' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher29_C, CurrentMenu) == 0x000628, "Member 'UAB_Menu_Slasher29_C::CurrentMenu' has a wrong offset!");
static_assert(offsetof(UAB_Menu_Slasher29_C, AnimSet) == 0x000630, "Member 'UAB_Menu_Slasher29_C::AnimSet' has a wrong offset!");

}

