#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AB_Menu_Haiti

#include "Basic.hpp"

#include "AB_Menu_Haiti_classes.hpp"
#include "AB_Menu_Haiti_parameters.hpp"


namespace SDK
{

// Function AB_Menu_Haiti.AB_Menu_Haiti_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UAB_Menu_Haiti_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Menu_Haiti_C", "AnimGraph");

	Params::AB_Menu_Haiti_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function AB_Menu_Haiti.AB_Menu_Haiti_C.BlueprintLinkedAnimationLayersInitialized
// (Event, Public, BlueprintEvent)

void UAB_Menu_Haiti_C::BlueprintLinkedAnimationLayersInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Menu_Haiti_C", "BlueprintLinkedAnimationLayersInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Menu_Haiti.AB_Menu_Haiti_C.ExecuteUbergraph_AB_Menu_Haiti
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAB_Menu_Haiti_C::ExecuteUbergraph_AB_Menu_Haiti(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Menu_Haiti_C", "ExecuteUbergraph_AB_Menu_Haiti");

	Params::AB_Menu_Haiti_C_ExecuteUbergraph_AB_Menu_Haiti Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

