#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AB_Menu_Camper

#include "Basic.hpp"

#include "Enum_CamperMenuAnimationState_structs.hpp"
#include "Engine_structs.hpp"
#include "DeadByDaylight_structs.hpp"


namespace SDK::Params
{

// Function AB_Menu_Camper.AB_Menu_Camper_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct AB_Menu_Camper_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
static_assert(alignof(AB_Menu_Camper_C_AnimGraph) == 0x000008, "Wrong alignment on AB_Menu_Camper_C_AnimGraph");
static_assert(sizeof(AB_Menu_Camper_C_AnimGraph) == 0x000010, "Wrong size on AB_Menu_Camper_C_AnimGraph");
static_assert(offsetof(AB_Menu_Camper_C_AnimGraph, AnimGraph_0) == 0x000000, "Member 'AB_Menu_Camper_C_AnimGraph::AnimGraph_0' has a wrong offset!");

// Function AB_Menu_Camper.AB_Menu_Camper_C.BlueprintUpdateAnimation
// 0x0004 (0x0004 - 0x0000)
struct AB_Menu_Camper_C_BlueprintUpdateAnimation final
{
public:
	float                                         DeltaTimeX;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AB_Menu_Camper_C_BlueprintUpdateAnimation) == 0x000004, "Wrong alignment on AB_Menu_Camper_C_BlueprintUpdateAnimation");
static_assert(sizeof(AB_Menu_Camper_C_BlueprintUpdateAnimation) == 0x000004, "Wrong size on AB_Menu_Camper_C_BlueprintUpdateAnimation");
static_assert(offsetof(AB_Menu_Camper_C_BlueprintUpdateAnimation, DeltaTimeX) == 0x000000, "Member 'AB_Menu_Camper_C_BlueprintUpdateAnimation::DeltaTimeX' has a wrong offset!");

// Function AB_Menu_Camper.AB_Menu_Camper_C.ExecuteUbergraph_AB_Menu_Camper
// 0x00D8 (0x00D8 - 0x0000)
struct AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_2;        // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_3;        // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_4;        // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_5;        // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x000B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_6;        // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_1;                  // 0x000D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_2;                  // 0x000E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_3;                  // 0x000F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_4;                  // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_7;        // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue_1;          // 0x0013(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Conv_BoolToDouble_ReturnValue;            // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue_2;          // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_22[0x6];                                       // 0x0022(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Conv_BoolToDouble_ReturnValue_1;          // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_8;        // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue_3;          // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_32[0x6];                                       // 0x0032(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Conv_BoolToDouble_ReturnValue_2;          // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_9;        // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_41[0x3];                                       // 0x0041(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetRelevantAnimTimeRemaining_ReturnValue; // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_10;       // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_DoubleDouble_ReturnValue;            // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NearlyEqual_FloatFloat_ReturnValue;       // 0x004A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B[0x1];                                       // 0x004B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Event_DeltaTimeX;                           // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_5;                  // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_2;                 // 0x0051(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	Enum_CamperMenuAnimationState                 K2Node_Event_state;                                // 0x0052(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_3;                 // 0x0053(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_TryGetPawnOwner_ReturnValue;              // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ADBDMenuPlayer*                         K2Node_DynamicCast_AsDBDMenu_Player;               // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EItemHandPosition                             CallFunc_GetHandPosition_ReturnValue;              // 0x0069(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue_4;          // 0x006A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6B[0x1];                                       // 0x006B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_RandomIntegerInRange_ReturnValue;         // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Conv_IntToDouble_ReturnValue;             // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsPlayingAnimation;                   // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0079(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7A[0x6];                                       // 0x007A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_Effect_Camper_Anim_C> K2Node_DynamicCast_AsBPI_Effect_Camper_Anim;   // 0x0080(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_91[0x3];                                       // 0x0091(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetRelevantAnimTimeRemaining_ReturnValue_1; // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_DoubleDouble_ReturnValue_1;          // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue_5;          // 0x0099(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NearlyEqual_FloatFloat_ReturnValue_1;     // 0x009A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_6;                  // 0x009B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_7;                  // 0x009C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9D[0x3];                                       // 0x009D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_StructMemberSet_Alpha_ImplicitCast;         // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Array_Set_Item_ImplicitCast;              // 0x00A4(0x0004)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Array_Set_Item_ImplicitCast_1;            // 0x00A8(0x0004)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_AC[0x4];                                       // 0x00AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_NearlyEqual_FloatFloat_A_ImplicitCast;    // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Less_DoubleDouble_A_ImplicitCast;         // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Delay_Duration_ImplicitCast;              // 0x00C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C4[0x4];                                       // 0x00C4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_NearlyEqual_FloatFloat_A_ImplicitCast_1;  // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Less_DoubleDouble_A_ImplicitCast_1;       // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper) == 0x000008, "Wrong alignment on AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper");
static_assert(sizeof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper) == 0x0000D8, "Wrong size on AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, EntryPoint) == 0x000000, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::EntryPoint' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x000004, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000005, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x000006, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_EqualEqual_ByteByte_ReturnValue_2) == 0x000007, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_EqualEqual_ByteByte_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_EqualEqual_ByteByte_ReturnValue_3) == 0x000008, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_EqualEqual_ByteByte_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_EqualEqual_ByteByte_ReturnValue_4) == 0x000009, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_EqualEqual_ByteByte_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_EqualEqual_ByteByte_ReturnValue_5) == 0x00000A, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_EqualEqual_ByteByte_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_BooleanOR_ReturnValue) == 0x00000B, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_EqualEqual_ByteByte_ReturnValue_6) == 0x00000C, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_EqualEqual_ByteByte_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_BooleanOR_ReturnValue_1) == 0x00000D, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_BooleanOR_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_BooleanOR_ReturnValue_2) == 0x00000E, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_BooleanOR_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_BooleanOR_ReturnValue_3) == 0x00000F, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_BooleanOR_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_BooleanOR_ReturnValue_4) == 0x000010, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_BooleanOR_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_EqualEqual_ByteByte_ReturnValue_7) == 0x000011, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_EqualEqual_ByteByte_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_BooleanAND_ReturnValue) == 0x000012, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_NotEqual_ByteByte_ReturnValue_1) == 0x000013, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_NotEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_Conv_BoolToDouble_ReturnValue) == 0x000018, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_Conv_BoolToDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_NotEqual_ByteByte_ReturnValue_2) == 0x000020, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_NotEqual_ByteByte_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_BooleanAND_ReturnValue_1) == 0x000021, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_Conv_BoolToDouble_ReturnValue_1) == 0x000028, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_Conv_BoolToDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_EqualEqual_ByteByte_ReturnValue_8) == 0x000030, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_EqualEqual_ByteByte_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_NotEqual_ByteByte_ReturnValue_3) == 0x000031, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_NotEqual_ByteByte_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_Conv_BoolToDouble_ReturnValue_2) == 0x000038, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_Conv_BoolToDouble_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_EqualEqual_ByteByte_ReturnValue_9) == 0x000040, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_EqualEqual_ByteByte_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_GetRelevantAnimTimeRemaining_ReturnValue) == 0x000044, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_GetRelevantAnimTimeRemaining_ReturnValue' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_EqualEqual_ByteByte_ReturnValue_10) == 0x000048, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_EqualEqual_ByteByte_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_Less_DoubleDouble_ReturnValue) == 0x000049, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_Less_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_NearlyEqual_FloatFloat_ReturnValue) == 0x00004A, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_NearlyEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, K2Node_Event_DeltaTimeX) == 0x00004C, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::K2Node_Event_DeltaTimeX' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_BooleanOR_ReturnValue_5) == 0x000050, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_BooleanOR_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_BooleanAND_ReturnValue_2) == 0x000051, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_BooleanAND_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, K2Node_Event_state) == 0x000052, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::K2Node_Event_state' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_BooleanAND_ReturnValue_3) == 0x000053, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_BooleanAND_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_TryGetPawnOwner_ReturnValue) == 0x000058, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_TryGetPawnOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, K2Node_DynamicCast_AsDBDMenu_Player) == 0x000060, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::K2Node_DynamicCast_AsDBDMenu_Player' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, K2Node_DynamicCast_bSuccess) == 0x000068, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_GetHandPosition_ReturnValue) == 0x000069, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_GetHandPosition_ReturnValue' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_NotEqual_ByteByte_ReturnValue_4) == 0x00006A, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_NotEqual_ByteByte_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_RandomIntegerInRange_ReturnValue) == 0x00006C, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_RandomIntegerInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_Conv_IntToDouble_ReturnValue) == 0x000070, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_Conv_IntToDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, K2Node_Event_IsPlayingAnimation) == 0x000078, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::K2Node_Event_IsPlayingAnimation' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_IsValid_ReturnValue) == 0x000079, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, K2Node_DynamicCast_AsBPI_Effect_Camper_Anim) == 0x000080, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::K2Node_DynamicCast_AsBPI_Effect_Camper_Anim' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, K2Node_DynamicCast_bSuccess_1) == 0x000090, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_GetRelevantAnimTimeRemaining_ReturnValue_1) == 0x000094, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_GetRelevantAnimTimeRemaining_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_Less_DoubleDouble_ReturnValue_1) == 0x000098, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_Less_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_NotEqual_ByteByte_ReturnValue_5) == 0x000099, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_NotEqual_ByteByte_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_NearlyEqual_FloatFloat_ReturnValue_1) == 0x00009A, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_NearlyEqual_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_BooleanOR_ReturnValue_6) == 0x00009B, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_BooleanOR_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_BooleanOR_ReturnValue_7) == 0x00009C, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_BooleanOR_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, K2Node_StructMemberSet_Alpha_ImplicitCast) == 0x0000A0, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::K2Node_StructMemberSet_Alpha_ImplicitCast' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_Array_Set_Item_ImplicitCast) == 0x0000A4, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_Array_Set_Item_ImplicitCast' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_Array_Set_Item_ImplicitCast_1) == 0x0000A8, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_Array_Set_Item_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_NearlyEqual_FloatFloat_A_ImplicitCast) == 0x0000B0, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_NearlyEqual_FloatFloat_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_Less_DoubleDouble_A_ImplicitCast) == 0x0000B8, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_Less_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_Delay_Duration_ImplicitCast) == 0x0000C0, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_Delay_Duration_ImplicitCast' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_NearlyEqual_FloatFloat_A_ImplicitCast_1) == 0x0000C8, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_NearlyEqual_FloatFloat_A_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper, CallFunc_Less_DoubleDouble_A_ImplicitCast_1) == 0x0000D0, "Member 'AB_Menu_Camper_C_ExecuteUbergraph_AB_Menu_Camper::CallFunc_Less_DoubleDouble_A_ImplicitCast_1' has a wrong offset!");

// Function AB_Menu_Camper.AB_Menu_Camper_C.Get_BP_MenuBaseCamper
// 0x0008 (0x0008 - 0x0000)
struct AB_Menu_Camper_C_Get_BP_MenuBaseCamper final
{
public:
	class ABP_Menu_Base_Camper_C*                 BP_MenuBaseCamper;                                 // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AB_Menu_Camper_C_Get_BP_MenuBaseCamper) == 0x000008, "Wrong alignment on AB_Menu_Camper_C_Get_BP_MenuBaseCamper");
static_assert(sizeof(AB_Menu_Camper_C_Get_BP_MenuBaseCamper) == 0x000008, "Wrong size on AB_Menu_Camper_C_Get_BP_MenuBaseCamper");
static_assert(offsetof(AB_Menu_Camper_C_Get_BP_MenuBaseCamper, BP_MenuBaseCamper) == 0x000000, "Member 'AB_Menu_Camper_C_Get_BP_MenuBaseCamper::BP_MenuBaseCamper' has a wrong offset!");

// Function AB_Menu_Camper.AB_Menu_Camper_C.GetCamperMenuAnimationState
// 0x0001 (0x0001 - 0x0000)
struct AB_Menu_Camper_C_GetCamperMenuAnimationState final
{
public:
	Enum_CamperMenuAnimationState                 MenuAnimationState;                                // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AB_Menu_Camper_C_GetCamperMenuAnimationState) == 0x000001, "Wrong alignment on AB_Menu_Camper_C_GetCamperMenuAnimationState");
static_assert(sizeof(AB_Menu_Camper_C_GetCamperMenuAnimationState) == 0x000001, "Wrong size on AB_Menu_Camper_C_GetCamperMenuAnimationState");
static_assert(offsetof(AB_Menu_Camper_C_GetCamperMenuAnimationState, MenuAnimationState) == 0x000000, "Member 'AB_Menu_Camper_C_GetCamperMenuAnimationState::MenuAnimationState' has a wrong offset!");

// Function AB_Menu_Camper.AB_Menu_Camper_C.IsPlayingMenuInterrupt
// 0x0001 (0x0001 - 0x0000)
struct AB_Menu_Camper_C_IsPlayingMenuInterrupt final
{
public:
	bool                                          IsPlayingAnimation;                                // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AB_Menu_Camper_C_IsPlayingMenuInterrupt) == 0x000001, "Wrong alignment on AB_Menu_Camper_C_IsPlayingMenuInterrupt");
static_assert(sizeof(AB_Menu_Camper_C_IsPlayingMenuInterrupt) == 0x000001, "Wrong size on AB_Menu_Camper_C_IsPlayingMenuInterrupt");
static_assert(offsetof(AB_Menu_Camper_C_IsPlayingMenuInterrupt, IsPlayingAnimation) == 0x000000, "Member 'AB_Menu_Camper_C_IsPlayingMenuInterrupt::IsPlayingAnimation' has a wrong offset!");

// Function AB_Menu_Camper.AB_Menu_Camper_C.SetCamperMenuAnimationState
// 0x0001 (0x0001 - 0x0000)
struct AB_Menu_Camper_C_SetCamperMenuAnimationState final
{
public:
	Enum_CamperMenuAnimationState                 State;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AB_Menu_Camper_C_SetCamperMenuAnimationState) == 0x000001, "Wrong alignment on AB_Menu_Camper_C_SetCamperMenuAnimationState");
static_assert(sizeof(AB_Menu_Camper_C_SetCamperMenuAnimationState) == 0x000001, "Wrong size on AB_Menu_Camper_C_SetCamperMenuAnimationState");
static_assert(offsetof(AB_Menu_Camper_C_SetCamperMenuAnimationState, State) == 0x000000, "Member 'AB_Menu_Camper_C_SetCamperMenuAnimationState::State' has a wrong offset!");

}

