#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AB_Menu_Slasher34_SW01

#include "Basic.hpp"

#include "AB_Menu_Slasher34_SW01_classes.hpp"
#include "AB_Menu_Slasher34_SW01_parameters.hpp"


namespace SDK
{

// Function AB_Menu_Slasher34_SW01.AB_Menu_Slasher34_SW01_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UAB_Menu_Slasher34_SW01_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Menu_Slasher34_SW01_C", "AnimGraph");

	Params::AB_Menu_Slasher34_SW01_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function AB_Menu_Slasher34_SW01.AB_Menu_Slasher34_SW01_C.BlueprintInitializeAnimation
// (Event, Public, BlueprintEvent)

void UAB_Menu_Slasher34_SW01_C::BlueprintInitializeAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Menu_Slasher34_SW01_C", "BlueprintInitializeAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Menu_Slasher34_SW01.AB_Menu_Slasher34_SW01_C.BlueprintLinkedAnimationLayersInitialized
// (Event, Public, BlueprintEvent)

void UAB_Menu_Slasher34_SW01_C::BlueprintLinkedAnimationLayersInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Menu_Slasher34_SW01_C", "BlueprintLinkedAnimationLayersInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AB_Menu_Slasher34_SW01.AB_Menu_Slasher34_SW01_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAB_Menu_Slasher34_SW01_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Menu_Slasher34_SW01_C", "BlueprintUpdateAnimation");

	Params::AB_Menu_Slasher34_SW01_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AB_Menu_Slasher34_SW01.AB_Menu_Slasher34_SW01_C.ExecuteUbergraph_AB_Menu_Slasher34_SW01
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAB_Menu_Slasher34_SW01_C::ExecuteUbergraph_AB_Menu_Slasher34_SW01(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AB_Menu_Slasher34_SW01_C", "ExecuteUbergraph_AB_Menu_Slasher34_SW01");

	Params::AB_Menu_Slasher34_SW01_C_ExecuteUbergraph_AB_Menu_Slasher34_SW01 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

