#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AB_S29_Tablete

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function AB_S29_Tablete.AB_S29_Tablete_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct AB_S29_Tablete_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
static_assert(alignof(AB_S29_Tablete_C_AnimGraph) == 0x000008, "Wrong alignment on AB_S29_Tablete_C_AnimGraph");
static_assert(sizeof(AB_S29_Tablete_C_AnimGraph) == 0x000010, "Wrong size on AB_S29_Tablete_C_AnimGraph");
static_assert(offsetof(AB_S29_Tablete_C_AnimGraph, AnimGraph_0) == 0x000000, "Member 'AB_S29_Tablete_C_AnimGraph::AnimGraph_0' has a wrong offset!");

// Function AB_S29_Tablete.AB_S29_Tablete_C.ExecuteUbergraph_AB_S29_Tablete
// 0x0004 (0x0004 - 0x0000)
struct AB_S29_Tablete_C_ExecuteUbergraph_AB_S29_Tablete final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AB_S29_Tablete_C_ExecuteUbergraph_AB_S29_Tablete) == 0x000004, "Wrong alignment on AB_S29_Tablete_C_ExecuteUbergraph_AB_S29_Tablete");
static_assert(sizeof(AB_S29_Tablete_C_ExecuteUbergraph_AB_S29_Tablete) == 0x000004, "Wrong size on AB_S29_Tablete_C_ExecuteUbergraph_AB_S29_Tablete");
static_assert(offsetof(AB_S29_Tablete_C_ExecuteUbergraph_AB_S29_Tablete, EntryPoint) == 0x000000, "Member 'AB_S29_Tablete_C_ExecuteUbergraph_AB_S29_Tablete::EntryPoint' has a wrong offset!");

}

