#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AB_Slasher_SubGraph_Menu

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// ScriptStruct AB_Slasher_SubGraph_Menu.AB_Slasher_SubGraph_Menu_C.AnimBlueprintGeneratedConstantData
// 0x01A7 (0x01A8 - 0x0001)
struct AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData final : public FAnimBlueprintConstantData
{
public:
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   __NameProperty_179;                                // 0x0004(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_180;                                // 0x0010(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_181;                                // 0x001C(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_182;                                 // 0x0028(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_183;                                // 0x002C(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<float>                                 __ArrayProperty_184;                               // 0x0038(0x0010)(BlueprintVisible, EditFixedSize)
	TArray<int32>                                 __ArrayProperty_185;                               // 0x0048(0x0010)(BlueprintVisible)
	class FName                                   __NameProperty_186;                                // 0x0058(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_187;                                 // 0x0064(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_188;                                // 0x0068(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_189;                                 // 0x0074(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBlendProfile*                          __BlendProfile_190;                                // 0x0078(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UCurveFloat*                            __CurveFloat_191;                                  // 0x0080(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	EAlphaBlendOption                             __EnumProperty_192;                                // 0x0088(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBlendListTransitionType                      __EnumProperty_193;                                // 0x0089(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8A[0x6];                                       // 0x008A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 __ArrayProperty_194;                               // 0x0090(0x0010)(BlueprintVisible, EditFixedSize)
	struct FAnimNodeFunctionRef                   __StructProperty_195;                              // 0x00A0(0x0028)(BlueprintVisible, NoDestructor)
	bool                                          __BoolProperty_196;                                // 0x00C8(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C9[0x3];                                       // 0x00C9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __FloatProperty_197;                               // 0x00CC(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FInputScaleBiasClampConstants          __StructProperty_198;                              // 0x00D0(0x002C)(BlueprintVisible, NoDestructor)
	float                                         __FloatProperty_199;                               // 0x00FC(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_200;                                // 0x0100(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAnimSyncMethod                               __EnumProperty_201;                                // 0x0101(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAnimGroupRole                                __ByteProperty_202;                                // 0x0102(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_103[0x1];                                      // 0x0103(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   __NameProperty_203;                                // 0x0104(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAnimSubsystem_PropertyAccess          AnimBlueprintExtension_PropertyAccess;             // 0x0110(0x0080)()
	struct FAnimSubsystem_Base                    AnimBlueprintExtension_Base;                       // 0x0190(0x0018)()
};
static_assert(alignof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData) == 0x0001A8, "Wrong size on AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData, __NameProperty_179) == 0x000004, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData::__NameProperty_179' has a wrong offset!");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData, __NameProperty_180) == 0x000010, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData::__NameProperty_180' has a wrong offset!");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData, __NameProperty_181) == 0x00001C, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData::__NameProperty_181' has a wrong offset!");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData, __IntProperty_182) == 0x000028, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData::__IntProperty_182' has a wrong offset!");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData, __NameProperty_183) == 0x00002C, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData::__NameProperty_183' has a wrong offset!");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData, __ArrayProperty_184) == 0x000038, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData::__ArrayProperty_184' has a wrong offset!");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData, __ArrayProperty_185) == 0x000048, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData::__ArrayProperty_185' has a wrong offset!");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData, __NameProperty_186) == 0x000058, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData::__NameProperty_186' has a wrong offset!");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData, __IntProperty_187) == 0x000064, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData::__IntProperty_187' has a wrong offset!");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData, __NameProperty_188) == 0x000068, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData::__NameProperty_188' has a wrong offset!");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData, __IntProperty_189) == 0x000074, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData::__IntProperty_189' has a wrong offset!");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData, __BlendProfile_190) == 0x000078, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData::__BlendProfile_190' has a wrong offset!");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData, __CurveFloat_191) == 0x000080, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData::__CurveFloat_191' has a wrong offset!");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData, __EnumProperty_192) == 0x000088, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData::__EnumProperty_192' has a wrong offset!");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData, __EnumProperty_193) == 0x000089, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData::__EnumProperty_193' has a wrong offset!");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData, __ArrayProperty_194) == 0x000090, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData::__ArrayProperty_194' has a wrong offset!");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData, __StructProperty_195) == 0x0000A0, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData::__StructProperty_195' has a wrong offset!");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData, __BoolProperty_196) == 0x0000C8, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData::__BoolProperty_196' has a wrong offset!");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData, __FloatProperty_197) == 0x0000CC, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData::__FloatProperty_197' has a wrong offset!");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData, __StructProperty_198) == 0x0000D0, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData::__StructProperty_198' has a wrong offset!");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData, __FloatProperty_199) == 0x0000FC, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData::__FloatProperty_199' has a wrong offset!");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData, __BoolProperty_200) == 0x000100, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData::__BoolProperty_200' has a wrong offset!");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData, __EnumProperty_201) == 0x000101, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData::__EnumProperty_201' has a wrong offset!");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData, __ByteProperty_202) == 0x000102, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData::__ByteProperty_202' has a wrong offset!");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData, __NameProperty_203) == 0x000104, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData::__NameProperty_203' has a wrong offset!");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData, AnimBlueprintExtension_PropertyAccess) == 0x000110, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData, AnimBlueprintExtension_Base) == 0x000190, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedConstantData::AnimBlueprintExtension_Base' has a wrong offset!");

// ScriptStruct AB_Slasher_SubGraph_Menu.AB_Slasher_SubGraph_Menu_C.AnimBlueprintGeneratedMutableData
// 0x0002 (0x0003 - 0x0001)
struct AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedMutableData final : public FAnimBlueprintMutableData
{
public:
	uint8                                         __ByteProperty;                                    // 0x0001(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_0;                                  // 0x0002(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedMutableData) == 0x000001, "Wrong alignment on AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedMutableData");
static_assert(sizeof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedMutableData) == 0x000003, "Wrong size on AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedMutableData");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedMutableData, __ByteProperty) == 0x000001, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedMutableData::__ByteProperty' has a wrong offset!");
static_assert(offsetof(AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedMutableData, __BoolProperty_0) == 0x000002, "Member 'AB_Slasher_SubGraph_Menu::FAnimBlueprintGeneratedMutableData::__BoolProperty_0' has a wrong offset!");

}

