#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Aset_Slasher_Menu

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct Aset_Slasher_Menu.Aset_Slasher_Menu
// 0x0050 (0x0050 - 0x0000)
struct FAset_Slasher_Menu final
{
public:
	class UAnimSequence*                          MenuIdle_18_FFD6BA49453CFEA6D8A893B6109C431F;      // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAnimSequence*                          MenuIdleInterrupt01_19_31F0358C4D2070DFC9142F820362D54F; // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAnimSequence*                          MenuIdleInterrupt02_22_0519AE00431F80436F2653995DB3AF63; // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAnimSequence*                          MenuIdleInterrupt03_31_C1F95CFA4C45F6264D96208B339E40A2; // 0x0018(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAnimSequence*                          MenuLobby_24_C8A98D004AFAB046DEA1529B43BB53F8;     // 0x0020(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAnimSequence*                          MenuLobbyInterrupt01_41_75F3B2574E85EC8A15382CA649211494; // 0x0028(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAnimSequence*                          MenuBack_26_5BC791FF46DC296AA28C3CAE26F2591B;      // 0x0030(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAnimSequence*                          MenuIntro001_46_284510EE45181F7FA26751A57DC44D5E;  // 0x0038(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAnimSequence*                          MenuIntro002_48_B0DDA4814C991695A1FE57B92E5C7AB5;  // 0x0040(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAnimSequence*                          MenuIntro003_50_A6C2ED1A480164A6795C7483EE38FC66;  // 0x0048(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(FAset_Slasher_Menu) == 0x000008, "Wrong alignment on FAset_Slasher_Menu");
static_assert(sizeof(FAset_Slasher_Menu) == 0x000050, "Wrong size on FAset_Slasher_Menu");
static_assert(offsetof(FAset_Slasher_Menu, MenuIdle_18_FFD6BA49453CFEA6D8A893B6109C431F) == 0x000000, "Member 'FAset_Slasher_Menu::MenuIdle_18_FFD6BA49453CFEA6D8A893B6109C431F' has a wrong offset!");
static_assert(offsetof(FAset_Slasher_Menu, MenuIdleInterrupt01_19_31F0358C4D2070DFC9142F820362D54F) == 0x000008, "Member 'FAset_Slasher_Menu::MenuIdleInterrupt01_19_31F0358C4D2070DFC9142F820362D54F' has a wrong offset!");
static_assert(offsetof(FAset_Slasher_Menu, MenuIdleInterrupt02_22_0519AE00431F80436F2653995DB3AF63) == 0x000010, "Member 'FAset_Slasher_Menu::MenuIdleInterrupt02_22_0519AE00431F80436F2653995DB3AF63' has a wrong offset!");
static_assert(offsetof(FAset_Slasher_Menu, MenuIdleInterrupt03_31_C1F95CFA4C45F6264D96208B339E40A2) == 0x000018, "Member 'FAset_Slasher_Menu::MenuIdleInterrupt03_31_C1F95CFA4C45F6264D96208B339E40A2' has a wrong offset!");
static_assert(offsetof(FAset_Slasher_Menu, MenuLobby_24_C8A98D004AFAB046DEA1529B43BB53F8) == 0x000020, "Member 'FAset_Slasher_Menu::MenuLobby_24_C8A98D004AFAB046DEA1529B43BB53F8' has a wrong offset!");
static_assert(offsetof(FAset_Slasher_Menu, MenuLobbyInterrupt01_41_75F3B2574E85EC8A15382CA649211494) == 0x000028, "Member 'FAset_Slasher_Menu::MenuLobbyInterrupt01_41_75F3B2574E85EC8A15382CA649211494' has a wrong offset!");
static_assert(offsetof(FAset_Slasher_Menu, MenuBack_26_5BC791FF46DC296AA28C3CAE26F2591B) == 0x000030, "Member 'FAset_Slasher_Menu::MenuBack_26_5BC791FF46DC296AA28C3CAE26F2591B' has a wrong offset!");
static_assert(offsetof(FAset_Slasher_Menu, MenuIntro001_46_284510EE45181F7FA26751A57DC44D5E) == 0x000038, "Member 'FAset_Slasher_Menu::MenuIntro001_46_284510EE45181F7FA26751A57DC44D5E' has a wrong offset!");
static_assert(offsetof(FAset_Slasher_Menu, MenuIntro002_48_B0DDA4814C991695A1FE57B92E5C7AB5) == 0x000040, "Member 'FAset_Slasher_Menu::MenuIntro002_48_B0DDA4814C991695A1FE57B92E5C7AB5' has a wrong offset!");
static_assert(offsetof(FAset_Slasher_Menu, MenuIntro003_50_A6C2ED1A480164A6795C7483EE38FC66) == 0x000048, "Member 'FAset_Slasher_Menu::MenuIntro003_50_A6C2ED1A480164A6795C7483EE38FC66' has a wrong offset!");

}

