#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Audio_KLR_36

#include "Basic.hpp"

#include "BP_Audio_KLR_36_classes.hpp"
#include "BP_Audio_KLR_36_parameters.hpp"


namespace SDK
{

// Function BP_Audio_KLR_36.BP_Audio_KLR_36_C.ExecuteUbergraph_BP_Audio_KLR_36
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Audio_KLR_36_C::ExecuteUbergraph_BP_Audio_KLR_36(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Audio_KLR_36_C", "ExecuteUbergraph_BP_Audio_KLR_36");

	Params::BP_Audio_KLR_36_C_ExecuteUbergraph_BP_Audio_KLR_36 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Audio_KLR_36.BP_Audio_KLR_36_C.HitImpactOnSurvivorSFX
// (BlueprintCosmetic, Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASurvivor*                        Survivor                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// EAttackType                             attackType                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsWeaponHit                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Audio_KLR_36_C::HitImpactOnSurvivorSFX(class ASurvivor* Survivor, EAttackType attackType, bool IsWeaponHit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Audio_KLR_36_C", "HitImpactOnSurvivorSFX");

	Params::BP_Audio_KLR_36_C_HitImpactOnSurvivorSFX Parms{};

	Parms.Survivor = Survivor;
	Parms.attackType = attackType;
	Parms.IsWeaponHit = IsWeaponHit;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Audio_KLR_36.BP_Audio_KLR_36_C.IsCharacter
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class ADBDPlayer*                       CamperPlayer                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// TArray<class FString>&                  CharacterName                                          (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool*                                   IsCharacter_0                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Audio_KLR_36_C::IsCharacter(class ADBDPlayer* CamperPlayer, TArray<class FString>& CharacterName, bool* IsCharacter_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Audio_KLR_36_C", "IsCharacter");

	Params::BP_Audio_KLR_36_C_IsCharacter Parms{};

	Parms.CamperPlayer = CamperPlayer;
	Parms.CharacterName = std::move(CharacterName);

	UObject::ProcessEvent(Func, &Parms);

	CharacterName = std::move(Parms.CharacterName);

	if (IsCharacter_0 != nullptr)
		*IsCharacter_0 = Parms.IsCharacter_0;
}


// Function BP_Audio_KLR_36.BP_Audio_KLR_36_C.OnKillerSoundbankLoaded
// (Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// EAkResult                               Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Audio_KLR_36_C::OnKillerSoundbankLoaded(EAkResult Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Audio_KLR_36_C", "OnKillerSoundbankLoaded");

	Params::BP_Audio_KLR_36_C_OnKillerSoundbankLoaded Parms{};

	Parms.Result = Result;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Audio_KLR_36.BP_Audio_KLR_36_C.SelectAudioStatusStartEvent
// (Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    IsInMenu                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAkAudioEvent**                   AudioEvent                                             (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBP_Audio_KLR_36_C::SelectAudioStatusStartEvent(bool IsInMenu, class UAkAudioEvent** AudioEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Audio_KLR_36_C", "SelectAudioStatusStartEvent");

	Params::BP_Audio_KLR_36_C_SelectAudioStatusStartEvent Parms{};

	Parms.IsInMenu = IsInMenu;

	UObject::ProcessEvent(Func, &Parms);

	if (AudioEvent != nullptr)
		*AudioEvent = Parms.AudioEvent;
}

}

