#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Menu_CamperMale15

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Menu_CamperMale15.BP_Menu_CamperMale15_C.ExecuteUbergraph_BP_Menu_CamperMale15
// 0x001C (0x001C - 0x0000)
struct BP_Menu_CamperMale15_C_ExecuteUbergraph_BP_Menu_CamperMale15 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0014)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_K2_AttachToComponent_ReturnValue;         // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Menu_CamperMale15_C_ExecuteUbergraph_BP_Menu_CamperMale15) == 0x000004, "Wrong alignment on BP_Menu_CamperMale15_C_ExecuteUbergraph_BP_Menu_CamperMale15");
static_assert(sizeof(BP_Menu_CamperMale15_C_ExecuteUbergraph_BP_Menu_CamperMale15) == 0x00001C, "Wrong size on BP_Menu_CamperMale15_C_ExecuteUbergraph_BP_Menu_CamperMale15");
static_assert(offsetof(BP_Menu_CamperMale15_C_ExecuteUbergraph_BP_Menu_CamperMale15, EntryPoint) == 0x000000, "Member 'BP_Menu_CamperMale15_C_ExecuteUbergraph_BP_Menu_CamperMale15::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_Menu_CamperMale15_C_ExecuteUbergraph_BP_Menu_CamperMale15, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'BP_Menu_CamperMale15_C_ExecuteUbergraph_BP_Menu_CamperMale15::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_Menu_CamperMale15_C_ExecuteUbergraph_BP_Menu_CamperMale15, CallFunc_K2_AttachToComponent_ReturnValue) == 0x000018, "Member 'BP_Menu_CamperMale15_C_ExecuteUbergraph_BP_Menu_CamperMale15::CallFunc_K2_AttachToComponent_ReturnValue' has a wrong offset!");

}

