#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Menu_Slasher06

#include "Basic.hpp"

#include "BP_Menu_BaseSlasher_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Menu_Slasher06.BP_Menu_Slasher06_C
// 0x0010 (0x0980 - 0x0970)
class ABP_Menu_Slasher06_C final : public ABP_Menu_BaseSlasher_C
{
public:
	class UBP_Audio_KLR_06_C*                     BP_Audio_KLR_06;                                   // 0x0968(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDBDPlayerPositionOffsetComponent*      DBDPlayerPositionOffset;                           // 0x0970(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Menu_Slasher06_C">();
	}
	static class ABP_Menu_Slasher06_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Menu_Slasher06_C>();
	}
};
static_assert(alignof(ABP_Menu_Slasher06_C) == 0x000010, "Wrong alignment on ABP_Menu_Slasher06_C");
static_assert(sizeof(ABP_Menu_Slasher06_C) == 0x000980, "Wrong size on ABP_Menu_Slasher06_C");
static_assert(offsetof(ABP_Menu_Slasher06_C, BP_Audio_KLR_06) == 0x000968, "Member 'ABP_Menu_Slasher06_C::BP_Audio_KLR_06' has a wrong offset!");
static_assert(offsetof(ABP_Menu_Slasher06_C, DBDPlayerPositionOffset) == 0x000970, "Member 'ABP_Menu_Slasher06_C::DBDPlayerPositionOffset' has a wrong offset!");

}

