#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Menu_Slasher26

#include "Basic.hpp"

#include "Enum_MenuAnimationState_structs.hpp"
#include "DBDSharedTypes_structs.hpp"


namespace SDK::Params
{

// Function BP_Menu_Slasher26.BP_Menu_Slasher26_C.BndEvt__BP_Slasher_Character_14_CustomizedAudio_K2Node_ComponentBoundEvent_0_CustomizedAudioChangedDelegate__DelegateSignature
// 0x0018 (0x0018 - 0x0000)
struct BP_Menu_Slasher26_C_BndEvt__BP_Slasher_Character_14_CustomizedAudio_K2Node_ComponentBoundEvent_0_CustomizedAudioChangedDelegate__DelegateSignature final
{
public:
	EAudioCustomizationCategory                   category;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 switchState;                                       // 0x0008(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Menu_Slasher26_C_BndEvt__BP_Slasher_Character_14_CustomizedAudio_K2Node_ComponentBoundEvent_0_CustomizedAudioChangedDelegate__DelegateSignature) == 0x000008, "Wrong alignment on BP_Menu_Slasher26_C_BndEvt__BP_Slasher_Character_14_CustomizedAudio_K2Node_ComponentBoundEvent_0_CustomizedAudioChangedDelegate__DelegateSignature");
static_assert(sizeof(BP_Menu_Slasher26_C_BndEvt__BP_Slasher_Character_14_CustomizedAudio_K2Node_ComponentBoundEvent_0_CustomizedAudioChangedDelegate__DelegateSignature) == 0x000018, "Wrong size on BP_Menu_Slasher26_C_BndEvt__BP_Slasher_Character_14_CustomizedAudio_K2Node_ComponentBoundEvent_0_CustomizedAudioChangedDelegate__DelegateSignature");
static_assert(offsetof(BP_Menu_Slasher26_C_BndEvt__BP_Slasher_Character_14_CustomizedAudio_K2Node_ComponentBoundEvent_0_CustomizedAudioChangedDelegate__DelegateSignature, category) == 0x000000, "Member 'BP_Menu_Slasher26_C_BndEvt__BP_Slasher_Character_14_CustomizedAudio_K2Node_ComponentBoundEvent_0_CustomizedAudioChangedDelegate__DelegateSignature::category' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_BndEvt__BP_Slasher_Character_14_CustomizedAudio_K2Node_ComponentBoundEvent_0_CustomizedAudioChangedDelegate__DelegateSignature, switchState) == 0x000008, "Member 'BP_Menu_Slasher26_C_BndEvt__BP_Slasher_Character_14_CustomizedAudio_K2Node_ComponentBoundEvent_0_CustomizedAudioChangedDelegate__DelegateSignature::switchState' has a wrong offset!");

// Function BP_Menu_Slasher26.BP_Menu_Slasher26_C.ExecuteUbergraph_BP_Menu_Slasher26
// 0x0160 (0x0160 - 0x0000)
struct BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate;              // 0x000C(0x0014)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_3;                   // 0x0020(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_2;                   // 0x002C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_1;            // 0x0038(0x0014)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_1;                   // 0x004C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_2;            // 0x0058(0x0014)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName;                     // 0x006C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_3;            // 0x0078(0x0014)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   Temp_name_Variable;                                // 0x008C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(Enum_MenuAnimationState State)> K2Node_CreateDelegate_OutputDelegate_4;           // 0x0098(0x0014)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   Temp_name_Variable_1;                              // 0x00AC(0x000C)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   Temp_name_Variable_2;                              // 0x00B8(0x000C)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAudioCustomizationCategory                   K2Node_ComponentBoundEvent_category;               // 0x00C4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C5[0x3];                                       // 0x00C5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_ComponentBoundEvent_switchState;            // 0x00C8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	Enum_MenuAnimationState                       K2Node_CustomEvent_State;                          // 0x00D9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DA[0x6];                                       // 0x00DA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UPlayMontageCallbackProxy*              CallFunc_CreateProxyObjectForPlayMontage_ReturnValue; // 0x00E0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess_1;                    // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00E9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_EA[0x2];                                       // 0x00EA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x00EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class FName>                           CallFunc_GetCurrentCustomizationItems_ReturnValue; // 0x00F0(0x0010)(ReferenceParm)
	bool                                          CallFunc_Array_Contains_ReturnValue;               // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_Contains_ReturnValue_1;             // 0x0101(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0102(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_103[0x5];                                      // 0x0103(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class USkeletalMeshComponent*                 CallFunc_GetSkeletalMesh_ReturnValue;              // 0x0108(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponentBudgeted*         K2Node_DynamicCast_AsSkeletal_Mesh_Component_Budgeted; // 0x0110(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_119[0x7];                                      // 0x0119(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInterface*                     CallFunc_GetMaterial_ReturnValue;                  // 0x0120(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_AddUnique_ReturnValue;              // 0x0128(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x012C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12D[0x3];                                      // 0x012D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class USkeletalMeshComponentBudgeted*         CallFunc_Array_Get_Item;                           // 0x0130(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0138(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x013C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x013D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_13E[0x2];                                      // 0x013E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   K2Node_CustomEvent_NotifyName_4;                   // 0x0140(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_5;            // 0x014C(0x0014)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26) == 0x000008, "Wrong alignment on BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26");
static_assert(sizeof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26) == 0x000160, "Wrong size on BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, EntryPoint) == 0x000000, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, K2Node_CreateDelegate_OutputDelegate) == 0x00000C, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, K2Node_CustomEvent_NotifyName_3) == 0x000020, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::K2Node_CustomEvent_NotifyName_3' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, K2Node_CustomEvent_NotifyName_2) == 0x00002C, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::K2Node_CustomEvent_NotifyName_2' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, K2Node_CreateDelegate_OutputDelegate_1) == 0x000038, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, K2Node_CustomEvent_NotifyName_1) == 0x00004C, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::K2Node_CustomEvent_NotifyName_1' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, K2Node_CreateDelegate_OutputDelegate_2) == 0x000058, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, K2Node_CustomEvent_NotifyName) == 0x00006C, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::K2Node_CustomEvent_NotifyName' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, K2Node_CreateDelegate_OutputDelegate_3) == 0x000078, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, Temp_name_Variable) == 0x00008C, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::Temp_name_Variable' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, K2Node_CreateDelegate_OutputDelegate_4) == 0x000098, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, Temp_name_Variable_1) == 0x0000AC, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::Temp_name_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, Temp_name_Variable_2) == 0x0000B8, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::Temp_name_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, K2Node_ComponentBoundEvent_category) == 0x0000C4, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::K2Node_ComponentBoundEvent_category' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, K2Node_ComponentBoundEvent_switchState) == 0x0000C8, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::K2Node_ComponentBoundEvent_switchState' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, K2Node_SwitchEnum_CmpSuccess) == 0x0000D8, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, K2Node_CustomEvent_State) == 0x0000D9, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::K2Node_CustomEvent_State' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, CallFunc_CreateProxyObjectForPlayMontage_ReturnValue) == 0x0000E0, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::CallFunc_CreateProxyObjectForPlayMontage_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, K2Node_SwitchEnum_CmpSuccess_1) == 0x0000E8, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::K2Node_SwitchEnum_CmpSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, CallFunc_IsValid_ReturnValue) == 0x0000E9, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, Temp_int_Array_Index_Variable) == 0x0000EC, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, CallFunc_GetCurrentCustomizationItems_ReturnValue) == 0x0000F0, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::CallFunc_GetCurrentCustomizationItems_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, CallFunc_Array_Contains_ReturnValue) == 0x000100, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::CallFunc_Array_Contains_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, CallFunc_Array_Contains_ReturnValue_1) == 0x000101, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::CallFunc_Array_Contains_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, CallFunc_BooleanOR_ReturnValue) == 0x000102, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, CallFunc_GetSkeletalMesh_ReturnValue) == 0x000108, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::CallFunc_GetSkeletalMesh_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, K2Node_DynamicCast_AsSkeletal_Mesh_Component_Budgeted) == 0x000110, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::K2Node_DynamicCast_AsSkeletal_Mesh_Component_Budgeted' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, K2Node_DynamicCast_bSuccess) == 0x000118, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, CallFunc_GetMaterial_ReturnValue) == 0x000120, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::CallFunc_GetMaterial_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, CallFunc_Array_AddUnique_ReturnValue) == 0x000128, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::CallFunc_Array_AddUnique_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, CallFunc_IsValid_ReturnValue_1) == 0x00012C, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, CallFunc_Array_Get_Item) == 0x000130, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, CallFunc_Array_Length_ReturnValue) == 0x000138, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, CallFunc_Less_IntInt_ReturnValue) == 0x00013C, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, CallFunc_IsValid_ReturnValue_2) == 0x00013D, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, K2Node_CustomEvent_NotifyName_4) == 0x000140, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::K2Node_CustomEvent_NotifyName_4' has a wrong offset!");
static_assert(offsetof(BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26, K2Node_CreateDelegate_OutputDelegate_5) == 0x00014C, "Member 'BP_Menu_Slasher26_C_ExecuteUbergraph_BP_Menu_Slasher26::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");

// Function BP_Menu_Slasher26.BP_Menu_Slasher26_C.GetMenuAnimationState
// 0x0001 (0x0001 - 0x0000)
struct BP_Menu_Slasher26_C_GetMenuAnimationState final
{
public:
	Enum_MenuAnimationState                       MenuAnimationState;                                // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Menu_Slasher26_C_GetMenuAnimationState) == 0x000001, "Wrong alignment on BP_Menu_Slasher26_C_GetMenuAnimationState");
static_assert(sizeof(BP_Menu_Slasher26_C_GetMenuAnimationState) == 0x000001, "Wrong size on BP_Menu_Slasher26_C_GetMenuAnimationState");
static_assert(offsetof(BP_Menu_Slasher26_C_GetMenuAnimationState, MenuAnimationState) == 0x000000, "Member 'BP_Menu_Slasher26_C_GetMenuAnimationState::MenuAnimationState' has a wrong offset!");

// Function BP_Menu_Slasher26.BP_Menu_Slasher26_C.OnBlendOut_64980147466C70D6568DB5B98DD4A55E
// 0x000C (0x000C - 0x0000)
struct BP_Menu_Slasher26_C_OnBlendOut_64980147466C70D6568DB5B98DD4A55E final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Menu_Slasher26_C_OnBlendOut_64980147466C70D6568DB5B98DD4A55E) == 0x000004, "Wrong alignment on BP_Menu_Slasher26_C_OnBlendOut_64980147466C70D6568DB5B98DD4A55E");
static_assert(sizeof(BP_Menu_Slasher26_C_OnBlendOut_64980147466C70D6568DB5B98DD4A55E) == 0x00000C, "Wrong size on BP_Menu_Slasher26_C_OnBlendOut_64980147466C70D6568DB5B98DD4A55E");
static_assert(offsetof(BP_Menu_Slasher26_C_OnBlendOut_64980147466C70D6568DB5B98DD4A55E, NotifyName) == 0x000000, "Member 'BP_Menu_Slasher26_C_OnBlendOut_64980147466C70D6568DB5B98DD4A55E::NotifyName' has a wrong offset!");

// Function BP_Menu_Slasher26.BP_Menu_Slasher26_C.OnCompleted_64980147466C70D6568DB5B98DD4A55E
// 0x000C (0x000C - 0x0000)
struct BP_Menu_Slasher26_C_OnCompleted_64980147466C70D6568DB5B98DD4A55E final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Menu_Slasher26_C_OnCompleted_64980147466C70D6568DB5B98DD4A55E) == 0x000004, "Wrong alignment on BP_Menu_Slasher26_C_OnCompleted_64980147466C70D6568DB5B98DD4A55E");
static_assert(sizeof(BP_Menu_Slasher26_C_OnCompleted_64980147466C70D6568DB5B98DD4A55E) == 0x00000C, "Wrong size on BP_Menu_Slasher26_C_OnCompleted_64980147466C70D6568DB5B98DD4A55E");
static_assert(offsetof(BP_Menu_Slasher26_C_OnCompleted_64980147466C70D6568DB5B98DD4A55E, NotifyName) == 0x000000, "Member 'BP_Menu_Slasher26_C_OnCompleted_64980147466C70D6568DB5B98DD4A55E::NotifyName' has a wrong offset!");

// Function BP_Menu_Slasher26.BP_Menu_Slasher26_C.OnInterrupted_64980147466C70D6568DB5B98DD4A55E
// 0x000C (0x000C - 0x0000)
struct BP_Menu_Slasher26_C_OnInterrupted_64980147466C70D6568DB5B98DD4A55E final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Menu_Slasher26_C_OnInterrupted_64980147466C70D6568DB5B98DD4A55E) == 0x000004, "Wrong alignment on BP_Menu_Slasher26_C_OnInterrupted_64980147466C70D6568DB5B98DD4A55E");
static_assert(sizeof(BP_Menu_Slasher26_C_OnInterrupted_64980147466C70D6568DB5B98DD4A55E) == 0x00000C, "Wrong size on BP_Menu_Slasher26_C_OnInterrupted_64980147466C70D6568DB5B98DD4A55E");
static_assert(offsetof(BP_Menu_Slasher26_C_OnInterrupted_64980147466C70D6568DB5B98DD4A55E, NotifyName) == 0x000000, "Member 'BP_Menu_Slasher26_C_OnInterrupted_64980147466C70D6568DB5B98DD4A55E::NotifyName' has a wrong offset!");

// Function BP_Menu_Slasher26.BP_Menu_Slasher26_C.OnMenuAnimationStateChange_Event
// 0x0001 (0x0001 - 0x0000)
struct BP_Menu_Slasher26_C_OnMenuAnimationStateChange_Event final
{
public:
	Enum_MenuAnimationState                       State;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Menu_Slasher26_C_OnMenuAnimationStateChange_Event) == 0x000001, "Wrong alignment on BP_Menu_Slasher26_C_OnMenuAnimationStateChange_Event");
static_assert(sizeof(BP_Menu_Slasher26_C_OnMenuAnimationStateChange_Event) == 0x000001, "Wrong size on BP_Menu_Slasher26_C_OnMenuAnimationStateChange_Event");
static_assert(offsetof(BP_Menu_Slasher26_C_OnMenuAnimationStateChange_Event, State) == 0x000000, "Member 'BP_Menu_Slasher26_C_OnMenuAnimationStateChange_Event::State' has a wrong offset!");

// Function BP_Menu_Slasher26.BP_Menu_Slasher26_C.OnNotifyBegin_64980147466C70D6568DB5B98DD4A55E
// 0x000C (0x000C - 0x0000)
struct BP_Menu_Slasher26_C_OnNotifyBegin_64980147466C70D6568DB5B98DD4A55E final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Menu_Slasher26_C_OnNotifyBegin_64980147466C70D6568DB5B98DD4A55E) == 0x000004, "Wrong alignment on BP_Menu_Slasher26_C_OnNotifyBegin_64980147466C70D6568DB5B98DD4A55E");
static_assert(sizeof(BP_Menu_Slasher26_C_OnNotifyBegin_64980147466C70D6568DB5B98DD4A55E) == 0x00000C, "Wrong size on BP_Menu_Slasher26_C_OnNotifyBegin_64980147466C70D6568DB5B98DD4A55E");
static_assert(offsetof(BP_Menu_Slasher26_C_OnNotifyBegin_64980147466C70D6568DB5B98DD4A55E, NotifyName) == 0x000000, "Member 'BP_Menu_Slasher26_C_OnNotifyBegin_64980147466C70D6568DB5B98DD4A55E::NotifyName' has a wrong offset!");

// Function BP_Menu_Slasher26.BP_Menu_Slasher26_C.OnNotifyEnd_64980147466C70D6568DB5B98DD4A55E
// 0x000C (0x000C - 0x0000)
struct BP_Menu_Slasher26_C_OnNotifyEnd_64980147466C70D6568DB5B98DD4A55E final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Menu_Slasher26_C_OnNotifyEnd_64980147466C70D6568DB5B98DD4A55E) == 0x000004, "Wrong alignment on BP_Menu_Slasher26_C_OnNotifyEnd_64980147466C70D6568DB5B98DD4A55E");
static_assert(sizeof(BP_Menu_Slasher26_C_OnNotifyEnd_64980147466C70D6568DB5B98DD4A55E) == 0x00000C, "Wrong size on BP_Menu_Slasher26_C_OnNotifyEnd_64980147466C70D6568DB5B98DD4A55E");
static_assert(offsetof(BP_Menu_Slasher26_C_OnNotifyEnd_64980147466C70D6568DB5B98DD4A55E, NotifyName) == 0x000000, "Member 'BP_Menu_Slasher26_C_OnNotifyEnd_64980147466C70D6568DB5B98DD4A55E::NotifyName' has a wrong offset!");

}

