#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Menu_CamperMale04

#include "Basic.hpp"

#include "BP_Menu_CamperMale04_classes.hpp"
#include "BP_Menu_CamperMale04_parameters.hpp"


namespace SDK
{

// Function BP_Menu_CamperMale04.BP_Menu_CamperMale04_C.BeginDestroySequence_Internal
// (Event, Protected, BlueprintEvent)

void ABP_Menu_CamperMale04_C::BeginDestroySequence_Internal()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Menu_CamperMale04_C", "BeginDestroySequence_Internal");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Menu_CamperMale04.BP_Menu_CamperMale04_C.Cigarette__FinishedFunc
// (BlueprintEvent)

void ABP_Menu_CamperMale04_C::Cigarette__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Menu_CamperMale04_C", "Cigarette__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Menu_CamperMale04.BP_Menu_CamperMale04_C.Cigarette__UpdateFunc
// (BlueprintEvent)

void ABP_Menu_CamperMale04_C::Cigarette__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Menu_CamperMale04_C", "Cigarette__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Menu_CamperMale04.BP_Menu_CamperMale04_C.ExecuteUbergraph_BP_Menu_CamperMale04
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Menu_CamperMale04_C::ExecuteUbergraph_BP_Menu_CamperMale04(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Menu_CamperMale04_C", "ExecuteUbergraph_BP_Menu_CamperMale04");

	Params::BP_Menu_CamperMale04_C_ExecuteUbergraph_BP_Menu_CamperMale04 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Menu_CamperMale04.BP_Menu_CamperMale04_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Menu_CamperMale04_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Menu_CamperMale04_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

