#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Menu_CamperMale12

#include "Basic.hpp"

#include "BP_Menu_CamperMale12_classes.hpp"
#include "BP_Menu_CamperMale12_parameters.hpp"


namespace SDK
{

// Function BP_Menu_CamperMale12.BP_Menu_CamperMale12_C.ExecuteUbergraph_BP_Menu_CamperMale12
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Menu_CamperMale12_C::ExecuteUbergraph_BP_Menu_CamperMale12(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Menu_CamperMale12_C", "ExecuteUbergraph_BP_Menu_CamperMale12");

	Params::BP_Menu_CamperMale12_C_ExecuteUbergraph_BP_Menu_CamperMale12 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

