#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Menu_CamperMale21

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_Menu_CamperMale21.BP_Menu_CamperMale21_C.ExecuteUbergraph_BP_Menu_CamperMale21
// 0x0038 (0x0038 - 0x0000)
struct BP_Menu_CamperMale21_C_ExecuteUbergraph_BP_Menu_CamperMale21 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAB_Menu_S42_C*                         K2Node_DynamicCast_AsAB_Menu_S42;                  // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue_1;            // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAB_Lute_S42_C*                         K2Node_DynamicCast_AsAB_Lute_S42;                  // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_K2_AttachToComponent_ReturnValue;         // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EEndPlayReason                                K2Node_Event_EndPlayReason;                        // 0x0032(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Menu_CamperMale21_C_ExecuteUbergraph_BP_Menu_CamperMale21) == 0x000008, "Wrong alignment on BP_Menu_CamperMale21_C_ExecuteUbergraph_BP_Menu_CamperMale21");
static_assert(sizeof(BP_Menu_CamperMale21_C_ExecuteUbergraph_BP_Menu_CamperMale21) == 0x000038, "Wrong size on BP_Menu_CamperMale21_C_ExecuteUbergraph_BP_Menu_CamperMale21");
static_assert(offsetof(BP_Menu_CamperMale21_C_ExecuteUbergraph_BP_Menu_CamperMale21, EntryPoint) == 0x000000, "Member 'BP_Menu_CamperMale21_C_ExecuteUbergraph_BP_Menu_CamperMale21::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_Menu_CamperMale21_C_ExecuteUbergraph_BP_Menu_CamperMale21, CallFunc_GetAnimInstance_ReturnValue) == 0x000008, "Member 'BP_Menu_CamperMale21_C_ExecuteUbergraph_BP_Menu_CamperMale21::CallFunc_GetAnimInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Menu_CamperMale21_C_ExecuteUbergraph_BP_Menu_CamperMale21, K2Node_DynamicCast_AsAB_Menu_S42) == 0x000010, "Member 'BP_Menu_CamperMale21_C_ExecuteUbergraph_BP_Menu_CamperMale21::K2Node_DynamicCast_AsAB_Menu_S42' has a wrong offset!");
static_assert(offsetof(BP_Menu_CamperMale21_C_ExecuteUbergraph_BP_Menu_CamperMale21, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'BP_Menu_CamperMale21_C_ExecuteUbergraph_BP_Menu_CamperMale21::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_Menu_CamperMale21_C_ExecuteUbergraph_BP_Menu_CamperMale21, CallFunc_GetAnimInstance_ReturnValue_1) == 0x000020, "Member 'BP_Menu_CamperMale21_C_ExecuteUbergraph_BP_Menu_CamperMale21::CallFunc_GetAnimInstance_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Menu_CamperMale21_C_ExecuteUbergraph_BP_Menu_CamperMale21, K2Node_DynamicCast_AsAB_Lute_S42) == 0x000028, "Member 'BP_Menu_CamperMale21_C_ExecuteUbergraph_BP_Menu_CamperMale21::K2Node_DynamicCast_AsAB_Lute_S42' has a wrong offset!");
static_assert(offsetof(BP_Menu_CamperMale21_C_ExecuteUbergraph_BP_Menu_CamperMale21, K2Node_DynamicCast_bSuccess_1) == 0x000030, "Member 'BP_Menu_CamperMale21_C_ExecuteUbergraph_BP_Menu_CamperMale21::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_Menu_CamperMale21_C_ExecuteUbergraph_BP_Menu_CamperMale21, CallFunc_K2_AttachToComponent_ReturnValue) == 0x000031, "Member 'BP_Menu_CamperMale21_C_ExecuteUbergraph_BP_Menu_CamperMale21::CallFunc_K2_AttachToComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Menu_CamperMale21_C_ExecuteUbergraph_BP_Menu_CamperMale21, K2Node_Event_EndPlayReason) == 0x000032, "Member 'BP_Menu_CamperMale21_C_ExecuteUbergraph_BP_Menu_CamperMale21::K2Node_Event_EndPlayReason' has a wrong offset!");

// Function BP_Menu_CamperMale21.BP_Menu_CamperMale21_C.ReceiveEndPlay
// 0x0001 (0x0001 - 0x0000)
struct BP_Menu_CamperMale21_C_ReceiveEndPlay final
{
public:
	EEndPlayReason                                EndPlayReason;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Menu_CamperMale21_C_ReceiveEndPlay) == 0x000001, "Wrong alignment on BP_Menu_CamperMale21_C_ReceiveEndPlay");
static_assert(sizeof(BP_Menu_CamperMale21_C_ReceiveEndPlay) == 0x000001, "Wrong size on BP_Menu_CamperMale21_C_ReceiveEndPlay");
static_assert(offsetof(BP_Menu_CamperMale21_C_ReceiveEndPlay, EndPlayReason) == 0x000000, "Member 'BP_Menu_CamperMale21_C_ReceiveEndPlay::EndPlayReason' has a wrong offset!");

}

