#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_VFX_Slasher_36_AnimNotifies_Handler

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_VFX_Slasher_36_AnimNotifies_Handler.BP_VFX_Slasher_36_AnimNotifies_Handler_C.ExecuteUbergraph_BP_VFX_Slasher_36_AnimNotifies_Handler
// 0x0004 (0x0004 - 0x0000)
struct BP_VFX_Slasher_36_AnimNotifies_Handler_C_ExecuteUbergraph_BP_VFX_Slasher_36_AnimNotifies_Handler final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_ExecuteUbergraph_BP_VFX_Slasher_36_AnimNotifies_Handler) == 0x000004, "Wrong alignment on BP_VFX_Slasher_36_AnimNotifies_Handler_C_ExecuteUbergraph_BP_VFX_Slasher_36_AnimNotifies_Handler");
static_assert(sizeof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_ExecuteUbergraph_BP_VFX_Slasher_36_AnimNotifies_Handler) == 0x000004, "Wrong size on BP_VFX_Slasher_36_AnimNotifies_Handler_C_ExecuteUbergraph_BP_VFX_Slasher_36_AnimNotifies_Handler");
static_assert(offsetof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_ExecuteUbergraph_BP_VFX_Slasher_36_AnimNotifies_Handler, EntryPoint) == 0x000000, "Member 'BP_VFX_Slasher_36_AnimNotifies_Handler_C_ExecuteUbergraph_BP_VFX_Slasher_36_AnimNotifies_Handler::EntryPoint' has a wrong offset!");

// Function BP_VFX_Slasher_36_AnimNotifies_Handler.BP_VFX_Slasher_36_AnimNotifies_Handler_C.HandleAnimNotify
// 0x00E0 (0x00E0 - 0x0000)
struct BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify final
{
public:
	class AActor*                                 Player_0;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   NotifyName;                                        // 0x0008(0x000C)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ReturnValue;                                       // 0x0014(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UPB_K36_SkullHead01_C*                  Skull1;                                            // 0x0018(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FName                                   VFXNotifyName;                                     // 0x0020(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AKiller*                                My_Slasher;                                        // 0x0030(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, HasGetValueTypeHash)
	class ADBDBasePlayer*                         K2Node_DynamicCast_AsDBDBase_Player;               // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AKiller*                                K2Node_DynamicCast_AsKiller;                       // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_Effects_K36_C>    K2Node_DynamicCast_AsBPI_Effects_K36;              // 0x0058(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_69[0x7];                                       // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_Effects_K36_C>    K2Node_DynamicCast_AsBPI_Effects_K36_1;            // 0x0070(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_81[0x7];                                       // 0x0081(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_Effects_K36_C>    K2Node_DynamicCast_AsBPI_Effects_K36_2;            // 0x0088(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_99[0x7];                                       // 0x0099(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_Effects_K36_C>    K2Node_DynamicCast_AsBPI_Effects_K36_3;            // 0x00A0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_5;                     // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B1[0x7];                                       // 0x00B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_Effects_K36_C>    K2Node_DynamicCast_AsBPI_Effects_K36_4;            // 0x00B8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_6;                     // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C9[0x7];                                       // 0x00C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AK36Spikes*                             CallFunc_GetSpikes_ReturnValue;                    // 0x00D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchName_CmpSuccess;                      // 0x00D9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HandleKillerNotifies_WallBreak_Return_Value; // 0x00DA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchName_CmpSuccess_1;                    // 0x00DB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HandleKillerNotifies_General_ReturnValue; // 0x00DC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify) == 0x000008, "Wrong alignment on BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify");
static_assert(sizeof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify) == 0x0000E0, "Wrong size on BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify");
static_assert(offsetof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify, Player_0) == 0x000000, "Member 'BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify::Player_0' has a wrong offset!");
static_assert(offsetof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify, NotifyName) == 0x000008, "Member 'BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify::NotifyName' has a wrong offset!");
static_assert(offsetof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify, ReturnValue) == 0x000014, "Member 'BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify, Skull1) == 0x000018, "Member 'BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify::Skull1' has a wrong offset!");
static_assert(offsetof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify, VFXNotifyName) == 0x000020, "Member 'BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify::VFXNotifyName' has a wrong offset!");
static_assert(offsetof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify, My_Slasher) == 0x000030, "Member 'BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify::My_Slasher' has a wrong offset!");
static_assert(offsetof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify, K2Node_DynamicCast_AsDBDBase_Player) == 0x000038, "Member 'BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify::K2Node_DynamicCast_AsDBDBase_Player' has a wrong offset!");
static_assert(offsetof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify, K2Node_DynamicCast_bSuccess) == 0x000040, "Member 'BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify, K2Node_DynamicCast_AsKiller) == 0x000048, "Member 'BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify::K2Node_DynamicCast_AsKiller' has a wrong offset!");
static_assert(offsetof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify, K2Node_DynamicCast_bSuccess_1) == 0x000050, "Member 'BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify, K2Node_DynamicCast_AsBPI_Effects_K36) == 0x000058, "Member 'BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify::K2Node_DynamicCast_AsBPI_Effects_K36' has a wrong offset!");
static_assert(offsetof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify, K2Node_DynamicCast_bSuccess_2) == 0x000068, "Member 'BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify, K2Node_DynamicCast_AsBPI_Effects_K36_1) == 0x000070, "Member 'BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify::K2Node_DynamicCast_AsBPI_Effects_K36_1' has a wrong offset!");
static_assert(offsetof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify, K2Node_DynamicCast_bSuccess_3) == 0x000080, "Member 'BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify, K2Node_DynamicCast_AsBPI_Effects_K36_2) == 0x000088, "Member 'BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify::K2Node_DynamicCast_AsBPI_Effects_K36_2' has a wrong offset!");
static_assert(offsetof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify, K2Node_DynamicCast_bSuccess_4) == 0x000098, "Member 'BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify, K2Node_DynamicCast_AsBPI_Effects_K36_3) == 0x0000A0, "Member 'BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify::K2Node_DynamicCast_AsBPI_Effects_K36_3' has a wrong offset!");
static_assert(offsetof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify, K2Node_DynamicCast_bSuccess_5) == 0x0000B0, "Member 'BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify::K2Node_DynamicCast_bSuccess_5' has a wrong offset!");
static_assert(offsetof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify, K2Node_DynamicCast_AsBPI_Effects_K36_4) == 0x0000B8, "Member 'BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify::K2Node_DynamicCast_AsBPI_Effects_K36_4' has a wrong offset!");
static_assert(offsetof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify, K2Node_DynamicCast_bSuccess_6) == 0x0000C8, "Member 'BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify::K2Node_DynamicCast_bSuccess_6' has a wrong offset!");
static_assert(offsetof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify, CallFunc_GetSpikes_ReturnValue) == 0x0000D0, "Member 'BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify::CallFunc_GetSpikes_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify, CallFunc_IsValid_ReturnValue) == 0x0000D8, "Member 'BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify, K2Node_SwitchName_CmpSuccess) == 0x0000D9, "Member 'BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify::K2Node_SwitchName_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify, CallFunc_HandleKillerNotifies_WallBreak_Return_Value) == 0x0000DA, "Member 'BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify::CallFunc_HandleKillerNotifies_WallBreak_Return_Value' has a wrong offset!");
static_assert(offsetof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify, K2Node_SwitchName_CmpSuccess_1) == 0x0000DB, "Member 'BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify::K2Node_SwitchName_CmpSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify, CallFunc_HandleKillerNotifies_General_ReturnValue) == 0x0000DC, "Member 'BP_VFX_Slasher_36_AnimNotifies_Handler_C_HandleAnimNotify::CallFunc_HandleKillerNotifies_General_ReturnValue' has a wrong offset!");

}

