#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_MenuSlasher

#include "Basic.hpp"

#include "BPI_MenuSlasher_classes.hpp"
#include "BPI_MenuSlasher_parameters.hpp"


namespace SDK
{

// Function BPI_MenuSlasher.BPI_MenuSlasher_C.GetMenuAnimationState
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// Enum_MenuAnimationState*                MenuAnimationState                                     (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBPI_MenuSlasher_C::GetMenuAnimationState(Enum_MenuAnimationState* MenuAnimationState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_MenuSlasher_C", "GetMenuAnimationState");

	Params::BPI_MenuSlasher_C_GetMenuAnimationState Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (MenuAnimationState != nullptr)
		*MenuAnimationState = Parms.MenuAnimationState;
}


// Function BPI_MenuSlasher.BPI_MenuSlasher_C.GetMenuBaseSlasher
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_Menu_BaseSlasher_C**          Bp_MenuBaseSlasher                                     (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void IBPI_MenuSlasher_C::GetMenuBaseSlasher(class ABP_Menu_BaseSlasher_C** Bp_MenuBaseSlasher)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_MenuSlasher_C", "GetMenuBaseSlasher");

	Params::BPI_MenuSlasher_C_GetMenuBaseSlasher Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (Bp_MenuBaseSlasher != nullptr)
		*Bp_MenuBaseSlasher = Parms.Bp_MenuBaseSlasher;
}


// Function BPI_MenuSlasher.BPI_MenuSlasher_C.OnMenuAnimationStateEnd
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// Enum_MenuAnimationState                 Ending_State                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBPI_MenuSlasher_C::OnMenuAnimationStateEnd(Enum_MenuAnimationState Ending_State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_MenuSlasher_C", "OnMenuAnimationStateEnd");

	Params::BPI_MenuSlasher_C_OnMenuAnimationStateEnd Parms{};

	Parms.Ending_State = Ending_State;

	AsUObject()->ProcessEvent(Func, &Parms);
}


// Function BPI_MenuSlasher.BPI_MenuSlasher_C.SetMenuAnimationState
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// Enum_MenuAnimationState                 State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBPI_MenuSlasher_C::SetMenuAnimationState(Enum_MenuAnimationState State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_MenuSlasher_C", "SetMenuAnimationState");

	Params::BPI_MenuSlasher_C_SetMenuAnimationState Parms{};

	Parms.State = State;

	AsUObject()->ProcessEvent(Func, &Parms);
}

}

