#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DBDProceduralCamera

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "DBDProceduralCamera_structs.hpp"


namespace SDK::Params
{

// Function DBDProceduralCamera.PCCameraSequencesConfig.GetSequence
// 0x0028 (0x0028 - 0x0000)
struct PCCameraSequencesConfig_GetSequence final
{
public:
	class FName                                   CharacterId;                                       // 0x0000(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FName>                           OutfitsID;                                         // 0x0010(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	class UProceduralCameraSequenceData*          ReturnValue;                                       // 0x0020(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PCCameraSequencesConfig_GetSequence) == 0x000008, "Wrong alignment on PCCameraSequencesConfig_GetSequence");
static_assert(sizeof(PCCameraSequencesConfig_GetSequence) == 0x000028, "Wrong size on PCCameraSequencesConfig_GetSequence");
static_assert(offsetof(PCCameraSequencesConfig_GetSequence, CharacterId) == 0x000000, "Member 'PCCameraSequencesConfig_GetSequence::CharacterId' has a wrong offset!");
static_assert(offsetof(PCCameraSequencesConfig_GetSequence, OutfitsID) == 0x000010, "Member 'PCCameraSequencesConfig_GetSequence::OutfitsID' has a wrong offset!");
static_assert(offsetof(PCCameraSequencesConfig_GetSequence, ReturnValue) == 0x000020, "Member 'PCCameraSequencesConfig_GetSequence::ReturnValue' has a wrong offset!");

// Function DBDProceduralCamera.PCCharacterSequenceOverride.GetSequence
// 0x0018 (0x0018 - 0x0000)
struct PCCharacterSequenceOverride_GetSequence final
{
public:
	TArray<class FName>                           OutfitsID;                                         // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	class UProceduralCameraSequenceData*          ReturnValue;                                       // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PCCharacterSequenceOverride_GetSequence) == 0x000008, "Wrong alignment on PCCharacterSequenceOverride_GetSequence");
static_assert(sizeof(PCCharacterSequenceOverride_GetSequence) == 0x000018, "Wrong size on PCCharacterSequenceOverride_GetSequence");
static_assert(offsetof(PCCharacterSequenceOverride_GetSequence, OutfitsID) == 0x000000, "Member 'PCCharacterSequenceOverride_GetSequence::OutfitsID' has a wrong offset!");
static_assert(offsetof(PCCharacterSequenceOverride_GetSequence, ReturnValue) == 0x000010, "Member 'PCCharacterSequenceOverride_GetSequence::ReturnValue' has a wrong offset!");

// Function DBDProceduralCamera.ProceduralCameraComponent.ClearLevelSequence
// 0x0010 (0x0010 - 0x0000)
struct ProceduralCameraComponent_ClearLevelSequence final
{
public:
	struct FGuid                                  CameraGuid;                                        // 0x0000(0x0010)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(ProceduralCameraComponent_ClearLevelSequence) == 0x000004, "Wrong alignment on ProceduralCameraComponent_ClearLevelSequence");
static_assert(sizeof(ProceduralCameraComponent_ClearLevelSequence) == 0x000010, "Wrong size on ProceduralCameraComponent_ClearLevelSequence");
static_assert(offsetof(ProceduralCameraComponent_ClearLevelSequence, CameraGuid) == 0x000000, "Member 'ProceduralCameraComponent_ClearLevelSequence::CameraGuid' has a wrong offset!");

// Function DBDProceduralCamera.ProceduralCameraComponent.GetCameraComponent
// 0x0008 (0x0008 - 0x0000)
struct ProceduralCameraComponent_GetCameraComponent final
{
public:
	class UCameraComponent*                       ReturnValue;                                       // 0x0000(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(ProceduralCameraComponent_GetCameraComponent) == 0x000008, "Wrong alignment on ProceduralCameraComponent_GetCameraComponent");
static_assert(sizeof(ProceduralCameraComponent_GetCameraComponent) == 0x000008, "Wrong size on ProceduralCameraComponent_GetCameraComponent");
static_assert(offsetof(ProceduralCameraComponent_GetCameraComponent, ReturnValue) == 0x000000, "Member 'ProceduralCameraComponent_GetCameraComponent::ReturnValue' has a wrong offset!");

// Function DBDProceduralCamera.ProceduralCameraComponent.GetSpawnedCameraActor
// 0x0008 (0x0008 - 0x0000)
struct ProceduralCameraComponent_GetSpawnedCameraActor final
{
public:
	class ACineCameraActor*                       ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(ProceduralCameraComponent_GetSpawnedCameraActor) == 0x000008, "Wrong alignment on ProceduralCameraComponent_GetSpawnedCameraActor");
static_assert(sizeof(ProceduralCameraComponent_GetSpawnedCameraActor) == 0x000008, "Wrong size on ProceduralCameraComponent_GetSpawnedCameraActor");
static_assert(offsetof(ProceduralCameraComponent_GetSpawnedCameraActor, ReturnValue) == 0x000000, "Member 'ProceduralCameraComponent_GetSpawnedCameraActor::ReturnValue' has a wrong offset!");

// Function DBDProceduralCamera.ProceduralCameraComponent.GetTargetActor
// 0x0008 (0x0008 - 0x0000)
struct ProceduralCameraComponent_GetTargetActor final
{
public:
	class AActor*                                 ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(ProceduralCameraComponent_GetTargetActor) == 0x000008, "Wrong alignment on ProceduralCameraComponent_GetTargetActor");
static_assert(sizeof(ProceduralCameraComponent_GetTargetActor) == 0x000008, "Wrong size on ProceduralCameraComponent_GetTargetActor");
static_assert(offsetof(ProceduralCameraComponent_GetTargetActor, ReturnValue) == 0x000000, "Member 'ProceduralCameraComponent_GetTargetActor::ReturnValue' has a wrong offset!");

// Function DBDProceduralCamera.ProceduralCameraComponent.GetTargetPlayer
// 0x0008 (0x0008 - 0x0000)
struct ProceduralCameraComponent_GetTargetPlayer final
{
public:
	class ADBDPlayer*                             ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(ProceduralCameraComponent_GetTargetPlayer) == 0x000008, "Wrong alignment on ProceduralCameraComponent_GetTargetPlayer");
static_assert(sizeof(ProceduralCameraComponent_GetTargetPlayer) == 0x000008, "Wrong size on ProceduralCameraComponent_GetTargetPlayer");
static_assert(offsetof(ProceduralCameraComponent_GetTargetPlayer, ReturnValue) == 0x000000, "Member 'ProceduralCameraComponent_GetTargetPlayer::ReturnValue' has a wrong offset!");

// Function DBDProceduralCamera.ProceduralCameraRaD.ComputeTrackObstructionScore
// 0x0018 (0x0018 - 0x0000)
struct ProceduralCameraRaD_ComputeTrackObstructionScore final
{
public:
	struct FCameraShot                            CameraShot;                                        // 0x0000(0x0018)(Parm, OutParm, NoDestructor, NativeAccessSpecifierPublic)
};
static_assert(alignof(ProceduralCameraRaD_ComputeTrackObstructionScore) == 0x000008, "Wrong alignment on ProceduralCameraRaD_ComputeTrackObstructionScore");
static_assert(sizeof(ProceduralCameraRaD_ComputeTrackObstructionScore) == 0x000018, "Wrong size on ProceduralCameraRaD_ComputeTrackObstructionScore");
static_assert(offsetof(ProceduralCameraRaD_ComputeTrackObstructionScore, CameraShot) == 0x000000, "Member 'ProceduralCameraRaD_ComputeTrackObstructionScore::CameraShot' has a wrong offset!");

// Function DBDProceduralCamera.ProceduralCameraRaD.OnCameraTransition
// 0x0008 (0x0008 - 0x0000)
struct ProceduralCameraRaD_OnCameraTransition final
{
public:
	float                                         TransitionDuration;                                // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         BeginAt;                                           // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(ProceduralCameraRaD_OnCameraTransition) == 0x000004, "Wrong alignment on ProceduralCameraRaD_OnCameraTransition");
static_assert(sizeof(ProceduralCameraRaD_OnCameraTransition) == 0x000008, "Wrong size on ProceduralCameraRaD_OnCameraTransition");
static_assert(offsetof(ProceduralCameraRaD_OnCameraTransition, TransitionDuration) == 0x000000, "Member 'ProceduralCameraRaD_OnCameraTransition::TransitionDuration' has a wrong offset!");
static_assert(offsetof(ProceduralCameraRaD_OnCameraTransition, BeginAt) == 0x000004, "Member 'ProceduralCameraRaD_OnCameraTransition::BeginAt' has a wrong offset!");

}

