#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TheS10

#include "Basic.hpp"

#include "DBDCompetence_structs.hpp"
#include "DeadByDaylight_classes.hpp"


namespace SDK
{

// Class TheS10.DeadHard
// 0x0090 (0x04F0 - 0x0460)
class UDeadHard final : public UPerk
{
public:
	TSubclassOf<class UDeadHardInteraction>       _deadHardInteraction;                              // 0x0460(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _deadHardCooldownDuration;                         // 0x0468(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_46C[0x4];                                      // 0x046C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FStatusEffectSpawnData>         _effectsToSpawn;                                   // 0x0470(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	struct FPlayerStatusEffectSpawnerHelper       _spawnerHelper;                                    // 0x0480(0x0050)(Transient, ContainsInstancedReference, NativeAccessSpecifierPrivate)
	TSubclassOf<class UStatusEffect>              _enduranceEffectClass;                             // 0x04D0(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _exhaustedCooldownPerLevel[0x3];                   // 0x04D8(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_4E4[0x4];                                      // 0x04E4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UInteractionAttacherComponent*          _interactionAttacherComponent;                     // 0x04E8(0x0008)(ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	float GetDeadHardCooldownDuration() const;
	float GetExhaustedDuration() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"DeadHard">();
	}
	static class UDeadHard* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDeadHard>();
	}
};
static_assert(alignof(UDeadHard) == 0x000008, "Wrong alignment on UDeadHard");
static_assert(sizeof(UDeadHard) == 0x0004F0, "Wrong size on UDeadHard");
static_assert(offsetof(UDeadHard, _deadHardInteraction) == 0x000460, "Member 'UDeadHard::_deadHardInteraction' has a wrong offset!");
static_assert(offsetof(UDeadHard, _deadHardCooldownDuration) == 0x000468, "Member 'UDeadHard::_deadHardCooldownDuration' has a wrong offset!");
static_assert(offsetof(UDeadHard, _effectsToSpawn) == 0x000470, "Member 'UDeadHard::_effectsToSpawn' has a wrong offset!");
static_assert(offsetof(UDeadHard, _spawnerHelper) == 0x000480, "Member 'UDeadHard::_spawnerHelper' has a wrong offset!");
static_assert(offsetof(UDeadHard, _enduranceEffectClass) == 0x0004D0, "Member 'UDeadHard::_enduranceEffectClass' has a wrong offset!");
static_assert(offsetof(UDeadHard, _exhaustedCooldownPerLevel) == 0x0004D8, "Member 'UDeadHard::_exhaustedCooldownPerLevel' has a wrong offset!");
static_assert(offsetof(UDeadHard, _interactionAttacherComponent) == 0x0004E8, "Member 'UDeadHard::_interactionAttacherComponent' has a wrong offset!");

// Class TheS10.DeadHardEffect
// 0x0000 (0x0398 - 0x0398)
class UDeadHardEffect final : public UStatusEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"DeadHardEffect">();
	}
	static class UDeadHardEffect* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDeadHardEffect>();
	}
};
static_assert(alignof(UDeadHardEffect) == 0x000008, "Wrong alignment on UDeadHardEffect");
static_assert(sizeof(UDeadHardEffect) == 0x000398, "Wrong size on UDeadHardEffect");

// Class TheS10.DeadHardInteraction
// 0x0010 (0x0780 - 0x0770)
class UDeadHardInteraction final : public UInteractionDefinition
{
public:
	uint8                                         Pad_768[0x18];                                     // 0x0768(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"DeadHardInteraction">();
	}
	static class UDeadHardInteraction* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDeadHardInteraction>();
	}
};
static_assert(alignof(UDeadHardInteraction) == 0x000010, "Wrong alignment on UDeadHardInteraction");
static_assert(sizeof(UDeadHardInteraction) == 0x000780, "Wrong size on UDeadHardInteraction");

}

