#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TheS30

#include "Basic.hpp"

#include "DeadByDaylight_classes.hpp"
#include "DBDCompetence_classes.hpp"


namespace SDK
{

// Class TheS30.S30P01
// 0x0010 (0x0470 - 0x0460)
class US30P01 final : public UPerk
{
public:
	float                                         _perkEffectActiveDuration[0x3];                    // 0x0460(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_46C[0x4];                                      // 0x046C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"S30P01">();
	}
	static class US30P01* GetDefaultObj()
	{
		return GetDefaultObjImpl<US30P01>();
	}
};
static_assert(alignof(US30P01) == 0x000008, "Wrong alignment on US30P01");
static_assert(sizeof(US30P01) == 0x000470, "Wrong size on US30P01");
static_assert(offsetof(US30P01, _perkEffectActiveDuration) == 0x000460, "Member 'US30P01::_perkEffectActiveDuration' has a wrong offset!");

// Class TheS30.S30P02
// 0x0048 (0x04A8 - 0x0460)
class US30P02 final : public UPerk
{
public:
	float                                         _auraReadingDistance[0x3];                         // 0x0460(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         _healingOthersBonus[0x3];                          // 0x046C(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_478[0x10];                                     // 0x0478(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UStatusEffect>              _revealAuraStatusEffectToImpose;                   // 0x0488(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TSubclassOf<class UStatusEffect>              _showHUDIconStatusEffectToImpose;                  // 0x0490(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TArray<class UStatusEffect*>                  _imposedShowHUDIconStatusEffects;                  // 0x0498(0x0010)(ExportObject, ZeroConstructor, Transient, ContainsInstancedReference, NativeAccessSpecifierPrivate)

public:
	const float GetHealingOthersBonus() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"S30P02">();
	}
	static class US30P02* GetDefaultObj()
	{
		return GetDefaultObjImpl<US30P02>();
	}
};
static_assert(alignof(US30P02) == 0x000008, "Wrong alignment on US30P02");
static_assert(sizeof(US30P02) == 0x0004A8, "Wrong size on US30P02");
static_assert(offsetof(US30P02, _auraReadingDistance) == 0x000460, "Member 'US30P02::_auraReadingDistance' has a wrong offset!");
static_assert(offsetof(US30P02, _healingOthersBonus) == 0x00046C, "Member 'US30P02::_healingOthersBonus' has a wrong offset!");
static_assert(offsetof(US30P02, _revealAuraStatusEffectToImpose) == 0x000488, "Member 'US30P02::_revealAuraStatusEffectToImpose' has a wrong offset!");
static_assert(offsetof(US30P02, _showHUDIconStatusEffectToImpose) == 0x000490, "Member 'US30P02::_showHUDIconStatusEffectToImpose' has a wrong offset!");
static_assert(offsetof(US30P02, _imposedShowHUDIconStatusEffects) == 0x000498, "Member 'US30P02::_imposedShowHUDIconStatusEffects' has a wrong offset!");

// Class TheS30.S30P03
// 0x0010 (0x0528 - 0x0518)
class US30P03 final : public UBoonPerk
{
public:
	float                                         _hasteLingerDuration[0x3];                         // 0x0518(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_524[0x4];                                      // 0x0524(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"S30P03">();
	}
	static class US30P03* GetDefaultObj()
	{
		return GetDefaultObjImpl<US30P03>();
	}
};
static_assert(alignof(US30P03) == 0x000008, "Wrong alignment on US30P03");
static_assert(sizeof(US30P03) == 0x000528, "Wrong size on US30P03");
static_assert(offsetof(US30P03, _hasteLingerDuration) == 0x000518, "Member 'US30P03::_hasteLingerDuration' has a wrong offset!");

}

