#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CoreRewardWrapperAnimation

#include "Basic.hpp"

#include "WBP_CoreRewardWrapperAnimation_classes.hpp"
#include "WBP_CoreRewardWrapperAnimation_parameters.hpp"


namespace SDK
{

// Function WBP_CoreRewardWrapperAnimation.WBP_CoreRewardWrapperAnimation_C.ExecuteUbergraph_WBP_CoreRewardWrapperAnimation
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CoreRewardWrapperAnimation_C::ExecuteUbergraph_WBP_CoreRewardWrapperAnimation(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CoreRewardWrapperAnimation_C", "ExecuteUbergraph_WBP_CoreRewardWrapperAnimation");

	Params::WBP_CoreRewardWrapperAnimation_C_ExecuteUbergraph_WBP_CoreRewardWrapperAnimation Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CoreRewardWrapperAnimation.WBP_CoreRewardWrapperAnimation_C.PlayClaimedAnim
// (BlueprintCallable, BlueprintEvent)

void UWBP_CoreRewardWrapperAnimation_C::PlayClaimedAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CoreRewardWrapperAnimation_C", "PlayClaimedAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CoreRewardWrapperAnimation.WBP_CoreRewardWrapperAnimation_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CoreRewardWrapperAnimation_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CoreRewardWrapperAnimation_C", "PreConstruct");

	Params::WBP_CoreRewardWrapperAnimation_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

